/**
 * @file AlarmBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-alarm-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M10.1213 3.05022C10.5118 2.65969 11.145 2.65969 11.5355 3.05022L12.9497 4.46443C13.3402 4.85496 13.3402 5.48812 12.9497 5.87864L5.87864 12.9497C5.48812 13.3402 4.85496 13.3402 4.46443 12.9497L3.05022 11.5355C2.65969 11.145 2.65969 10.5118 3.05022 10.1213L10.1213 3.05022ZM36.4644 3.05022C36.8549 2.65969 37.4881 2.65969 37.8786 3.05022L44.9497 10.1213C45.3402 10.5118 45.3402 11.145 44.9497 11.5355L43.5355 12.9497C43.145 13.3402 42.5118 13.3402 42.1213 12.9497L35.0502 5.87864C34.6597 5.48812 34.6597 4.85496 35.0502 4.46443L36.4644 3.05022ZM8.99996 26C8.99996 34.2842 15.7157 41 24 41C32.2842 41 39 34.2842 39 26C39 17.7157 32.2842 11 24 11C15.7157 11 8.99996 17.7157 8.99996 26ZM24 6.99997C13.5066 6.99997 4.99996 15.5066 4.99996 26C4.99996 36.4934 13.5066 45 24 45C34.4934 45 43 36.4934 43 26C43 15.5066 34.4934 6.99997 24 6.99997ZM22 17C22 16.4477 22.4477 16 23 16H25C25.5522 16 26 16.4477 26 17V27.3431L31.2857 32.6289C31.6763 33.0194 31.6763 33.6526 31.2857 34.0431L29.8715 35.4573C29.481 35.8479 28.8478 35.8479 28.4573 35.4573L22 29V17Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
