/**
 * @file ClockBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-clock-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7 24C7 33.3888 14.6112 41 24 41C33.3888 41 41 33.3888 41 24C41 14.6112 33.3888 7 24 7C14.6112 7 7 14.6112 7 24ZM24 3C12.402 3 3 12.402 3 24C3 35.598 12.402 45 24 45C35.598 45 45 35.598 45 24C45 12.402 35.598 3 24 3ZM22 11C22 10.4477 22.4477 10 23 10H25C25.5523 10 26 10.4477 26 11V24.3432L32.6065 30.9497C32.997 31.3403 32.997 31.9734 32.6065 32.364L31.1923 33.7782C30.8018 34.1687 30.1686 34.1687 29.7781 33.7782L22.707 26.7071C22.6032 26.6033 22.527 26.4823 22.4784 26.3533C22.1914 26.1776 22 25.8611 22 25.5V11Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
