/**
 * @file CloseBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-close-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M7.99907 8.91929L11.075 11.9952L11.9942 11.076L8.91831 8.00005L11.9942 4.92415L11.075 4.00491L7.99907 7.08081L4.92314 4.00488L4.00391 4.92412L7.07983 8.00005L4.00391 11.076L4.92314 11.9952L7.99907 8.91929Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
