/**
 * @file CopperBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-copper-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M45.7422 24C45.7422 35.598 36.3402 45 24.7422 45C13.1442 45 3.74219 35.598 3.74219 24C3.74219 12.402 13.1442 3 24.7422 3C36.3402 3 45.7422 12.402 45.7422 24ZM33.2275 24L24.7422 15.5147L16.2569 24L24.7422 32.4853L33.2275 24Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
