/**
 * @file DownBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-down-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M11.9952 6.49479L12.4899 5.99964L11.4996 5.01005L11.0048 5.50521L11.9952 6.49479ZM8.00258 9.5L7.50779 9.99515L8.00294 10.4899L8.49774 9.99479L8.00258 9.5ZM4.99479 5.50484L4.49963 5.01005L3.51005 6.00037L4.00521 6.49516L4.99479 5.50484ZM11.0048 5.50521L7.50742 9.0052L8.49774 9.99479L11.9952 6.49479L11.0048 5.50521ZM8.49737 9.00484L4.99479 5.50484L4.00521 6.49516L7.50779 9.99515L8.49737 9.00484Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
