/**
 * @file EditFormBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-edit-form-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M9 4.5C7.34315 4.5 6 5.84315 6 7.5V40.5C6 42.1569 7.34315 43.5 9 43.5H23.5839L23.9167 41.0004C24.0422 40.0577 24.5343 39.1066 25.2861 38.3538L36.2953 27.3287C36.6691 26.9543 37.0765 26.6424 37.5 26.395V7.5C37.5 5.84315 36.1569 4.5 34.5 4.5H9ZM30 15H13.5V18H30V15ZM13.5 23.25H22.5V26.25H13.5V23.25Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M27.2411 40.8715C27.2698 40.7257 27.3412 40.5917 27.4463 40.4865L38.1894 29.7299C38.7719 29.1466 39.716 29.1427 40.3033 29.7212L42.0107 31.4029C42.6036 31.9869 42.6078 32.942 42.0198 33.5311L31.2664 44.306C31.1611 44.4115 31.0268 44.4832 30.8806 44.5121L27.4445 45.1893C26.9212 45.2925 26.4605 44.8318 26.5636 44.3084L27.2411 40.8715Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
