/**
 * @file EditFormBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-edit-form-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M10 39.5V8.5H33.5V22.5H37.5V7.5C37.5 5.84315 36.1569 4.5 34.5 4.5H9C7.34315 4.5 6 5.84315 6 7.5V40.5C6 42.1569 7.34315 43.5 9 43.5H20.25V39.5H10ZM14.5 15C13.9477 15 13.5 15.4477 13.5 16V18C13.5 18.5523 13.9477 19 14.5 19H29C29.5523 19 30 18.5523 30 18V16C30 15.4477 29.5523 15 29 15H14.5ZM14.5 23.25C13.9477 23.25 13.5 23.6977 13.5 24.25V26.25C13.5 26.8023 13.9477 27.25 14.5 27.25H21.5C22.0523 27.25 22.5 26.8023 22.5 26.25V24.25C22.5 23.6977 22.0523 23.25 21.5 23.25H14.5ZM27.0117 42.4882L27.0216 39.9959L38.2625 28.7339L40.7493 31.1953L29.4995 42.4784L27.0117 42.4882ZM24.0253 39.0584C24.0261 38.8608 24.1048 38.6715 24.2445 38.5316L37.1945 25.5574C37.778 24.9728 38.7243 24.9699 39.3113 25.551L43.9297 30.1222C44.52 30.7065 44.5231 31.6592 43.9367 32.2474L30.9683 45.2542C30.8283 45.3946 30.6384 45.4739 30.4401 45.4746L24.7557 45.4972C24.3391 45.4988 24.001 45.1608 24.0027 44.7442L24.0253 39.0584Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
