/**
 * @file FemaleBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-female-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g clip-path="url(#clip0_22951:61608)">
                    <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M24.9746 1.5C12.5482 1.5 2.47461 11.5736 2.47461 24C2.47461 36.4264 12.5482 46.5 24.9746 46.5C37.401 46.5 47.4746 36.4264 47.4746 24C47.4746 11.5736 37.401 1.5 24.9746 1.5ZM30.9746 19.5C30.9746 22.8137 28.2883 25.5 24.9746 25.5C21.6609 25.5 18.9746 22.8137 18.9746 19.5C18.9746 16.1863 21.6609 13.5 24.9746 13.5C28.2883 13.5 30.9746 16.1863 30.9746 19.5ZM33.9746 19.5C33.9746 23.9595 30.7312 27.6614 26.4746 28.3756V31.5H31.7246C32.1388 31.5 32.4746 31.8358 32.4746 32.25V33.75C32.4746 34.1642 32.1388 34.5 31.7246 34.5H26.4746V39.75C26.4746 40.1642 26.1388 40.5 25.7246 40.5H24.2246C23.8104 40.5 23.4746 40.1642 23.4746 39.75V34.5H18.2246C17.8104 34.5 17.4746 34.1642 17.4746 33.75V32.25C17.4746 31.8358 17.8104 31.5 18.2246 31.5H23.4746V28.3756C19.218 27.6614 15.9746 23.9595 15.9746 19.5C15.9746 14.5294 20.004 10.5 24.9746 10.5C29.9452 10.5 33.9746 14.5294 33.9746 19.5Z"
                        fill={props.color}
                    />
                </g>
                <defs>
                    <clipPath id="clip0_22951:61608">
                        <rect
                            width="48"
                            height="48"
                            fill={props.color}
                            transform="translate(0.974609)"
                        />
                    </clipPath>
                </defs>
            </svg>
        );
    },
});
