/**
 * @file FormBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-form-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M8 4C6.89543 4 6 4.89543 6 6V42C6 43.1046 6.89543 44 8 44H40C41.1046 44 42 43.1046 42 42V6C42 4.89543 41.1046 4 40 4H8ZM18 14C17.4477 14 17 14.4477 17 15V17C17 17.5523 17.4477 18 18 18H30C30.5523 18 31 17.5523 31 17V15C31 14.4477 30.5523 14 30 14H18ZM18 22C17.4477 22 17 22.4477 17 23V25C17 25.5523 17.4477 26 18 26H30C30.5523 26 31 25.5523 31 25V23C31 22.4477 30.5523 22 30 22H18ZM17 31C17 30.4477 17.4477 30 18 30H23C23.5523 30 24 30.4477 24 31V33C24 33.5523 23.5523 34 23 34H18C17.4477 34 17 33.5523 17 33V31Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
