/**
 * @file HelpCircleBaseFilledPc
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-help-circle-base-filled-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M14.9961 8C14.9961 4.13401 11.8621 1 7.9961 1C4.1301 0.999998 0.996095 4.134 0.996094 8C0.996092 11.866 4.1301 15 7.99609 15C11.8621 15 14.9961 11.866 14.9961 8ZM5.80444 6.6315C5.80444 5.42262 6.78706 4.44 7.99594 4.44C9.20483 4.44 10.1874 5.42262 10.1874 6.6315C10.1874 7.60163 9.44485 8.35248 8.70295 8.65455C8.582 8.70488 8.49599 8.82451 8.49599 8.97008V9.7675H7.49599V8.97008C7.49599 8.41041 7.83484 7.931 8.32236 7.7298L8.32491 7.72875C8.81967 7.52775 9.18745 7.07185 9.18745 6.6315C9.18745 5.9749 8.65255 5.44 7.99594 5.44C7.33934 5.44 6.80444 5.9749 6.80444 6.6315H5.80444ZM7.46868 11.1734C7.46868 10.8823 7.70473 10.6462 7.9959 10.6462C8.28708 10.6462 8.52312 10.8823 8.52312 11.1734C8.52312 11.4646 8.28708 11.7007 7.9959 11.7007C7.70473 11.7007 7.46868 11.4646 7.46868 11.1734Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
