/**
 * @file HelpBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-help-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M21.75 33.75C21.75 32.9216 22.4216 32.25 23.25 32.25H24.75C25.5784 32.25 26.25 32.9216 26.25 33.75V35.25C26.25 36.0784 25.5784 36.75 24.75 36.75H23.25C22.4216 36.75 21.75 36.0784 21.75 35.25V33.75Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7 24C7 33.3888 14.6112 41 24 41C33.3888 41 41 33.3888 41 24C41 14.6112 33.3888 7 24 7C14.6112 7 7 14.6112 7 24ZM3 24C3 35.598 12.402 45 24 45C35.598 45 45 35.598 45 24C45 12.402 35.598 3 24 3C12.402 3 3 12.402 3 24Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M18.7504 19.1707C19.5787 19.1839 20.2371 18.4906 20.6131 17.7524C21.2014 16.597 22.4542 15.75 24.0001 15.75C26.1633 15.75 27.7505 17.4063 27.7505 19.2485C27.7505 19.9622 27.243 20.7252 26.0068 21.4912C23.9273 22.7799 21.7505 25.126 21.7502 28.2802C21.7502 28.8157 22.1843 29.2499 22.7198 29.2499L25.2805 29.2501C25.816 29.2501 26.2502 28.8161 26.2502 28.2805C26.2503 27.3259 26.9643 26.1919 28.3773 25.3163C30.0081 24.3056 32.2505 22.3659 32.2505 19.2485C32.2505 14.7411 28.4648 11.25 24.0001 11.25C20.085 11.25 16.6936 13.933 15.9166 17.6336C15.7464 18.4444 16.4223 19.1334 17.2506 19.1467L18.7504 19.1707Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
