/**
 * @file runtime 运行时
 * @author Auto Generated by IconPark
 */

import Vue, {ComponentOptions, CreateElement, VNode, VueConstructor} from 'vue2';
import {ArrayPropsDefinition, DefaultComputed, DefaultData, DefaultMethods} from 'vue2/types/options';
import { IIconProps } from '../type';

 


const render = (h: CreateElement, props: IIconProps) => (
  <svg
      width={props.size}
      height={props.size}
      viewBox="0 0 48 48"
      fill="none"
  >
      <path
          d="M44 24V9H24H4V24V39H24"
          stroke={props.color}
      />
      <path
          d="M44 34L30 34"
          stroke={props.color}
      />
  </svg>
);

export default {
  name: 'icon-',
  props: ['size', 'color'],
  data() {
      return {};
  },
  inheritAttrs: false,
  render(h: CreateElement): VNode {
      const svgProps: IIconProps = {
        size: this.size,
        color: this.color,
      };
    return render(h, svgProps);
  }
};
 