/**
 * @file InformationBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-information-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4ZM21.75 22C21.75 21.4477 22.1977 21 22.75 21L25.25 21C25.8023 21 26.25 21.4477 26.25 22L26.25 33.5C26.25 34.0523 25.8023 34.5 25.25 34.5L22.75 34.5C22.1977 34.5 21.75 34.0523 21.75 33.5L21.75 22ZM22.75 13.5C22.1977 13.5 21.75 13.9477 21.75 14.5L21.75 17C21.75 17.5523 22.1977 18 22.75 18L25.25 18C25.8023 18 26.25 17.5523 26.25 17L26.25 14.5C26.25 13.9477 25.8023 13.5 25.25 13.5L22.75 13.5Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
