/**
 * @file InformationBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-information-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#4A96FF",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g opacity="0.01">
                    <rect
                        x="0.5"
                        y="0.5"
                        width="47"
                        height="47"
                        rx="3.5"
                        fill={props.color}
                        stroke={props.color}
                    />
                    <path
                        opacity="0.2"
                        d="M24 13.25C29.9371 13.25 34.75 18.0629 34.75 24C34.75 29.9371 29.9371 34.75 24 34.75C18.0629 34.75 13.25 29.9371 13.25 24C13.25 18.0629 18.0629 13.25 24 13.25Z"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M24 16.25C28.2802 16.25 31.75 19.7198 31.75 24C31.75 28.2802 28.2802 31.75 24 31.75C19.7198 31.75 16.25 28.2802 16.25 24C16.25 19.7198 19.7198 16.25 24 16.25Z"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M0 12.9375H48"
                        stroke={props.color}
                    />
                    <path opacity="0.2" d="M0 24H48" stroke={props.color} />
                    <path opacity="0.2" d="M0 35.25H48" stroke={props.color} />
                    <path opacity="0.2" d="M24 48L24 0" stroke={props.color} />
                    <path opacity="0.2" d="M35.25 48V0" stroke={props.color} />
                    <path
                        opacity="0.2"
                        d="M12.75 48L12.75 0"
                        stroke={props.color}
                    />
                    <path
                        opacity="0.2"
                        d="M1.125 46.875L46.875 1.125"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M46.875 46.875L1.125 1.125"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        d="M11.5 4.55H36.5C38.6815 4.55 40.45 6.31848 40.45 8.5V39.5C40.45 41.6815 38.6815 43.45 36.5 43.45H11.5C9.31848 43.45 7.55 41.6815 7.55 39.5V8.5C7.55 6.31848 9.31848 4.55 11.5 4.55Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M4.55 36.5V11.5C4.55 9.31848 6.31848 7.55 8.5 7.55H39.5C41.6815 7.55 43.45 9.31848 43.45 11.5V36.5C43.45 38.6815 41.6815 40.45 39.5 40.45H8.5C6.31848 40.45 4.55 38.6815 4.55 36.5Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M6.05 38V10C6.05 7.81848 7.81848 6.05 10 6.05H38C40.1815 6.05 41.95 7.81848 41.95 10V38C41.95 40.1815 40.1815 41.95 38 41.95H10C7.81848 41.95 6.05 40.1815 6.05 38Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M24 4.55C34.7419 4.55 43.45 13.2581 43.45 24C43.45 34.7419 34.7419 43.45 24 43.45C13.2581 43.45 4.55 34.7419 4.55 24C4.55 13.2581 13.2581 4.55 24 4.55Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                </g>
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24 40.25C32.9746 40.25 40.25 32.9746 40.25 24C40.25 15.0254 32.9746 7.75 24 7.75C15.0254 7.75 7.75 15.0254 7.75 24C7.75 32.9746 15.0254 40.25 24 40.25ZM44.25 24C44.25 35.1838 35.1838 44.25 24 44.25C12.8162 44.25 3.75 35.1838 3.75 24C3.75 12.8162 12.8162 3.75 24 3.75C35.1838 3.75 44.25 12.8162 44.25 24ZM22 22C22 21.4477 22.4477 21 23 21H25C25.5523 21 26 21.4477 26 22L26 34C26 34.5523 25.5523 35 25 35H23C22.4477 35 22 34.5523 22 34L22 22ZM22.75 13.5C22.1977 13.5 21.75 13.9477 21.75 14.5V17C21.75 17.5523 22.1977 18 22.75 18H25.25C25.8023 18 26.25 17.5523 26.25 17V14.5C26.25 13.9477 25.8023 13.5 25.25 13.5H22.75Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
