/**
 * @file JumpPageBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-jump-page-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M39.9999 9.61089C39.9999 8.72122 39.2787 8 38.389 8H10.0632C9.51603 8 9.07047 8.43975 9.06329 8.98687L9.01314 12.8064C9.00585 13.3611 9.45155 13.8157 10.0063 13.8195L30.1046 13.9548L6.70479 37.5053C6.31552 37.8971 6.31552 38.5323 6.70479 38.924L9.52413 41.7615C9.9134 42.1533 10.5445 42.1533 10.9338 41.7615L34.0492 18.4973L34.1804 37.9936C34.1842 38.5484 34.6388 38.9941 35.1936 38.9868L39.0131 38.9366C39.5602 38.9295 39.9999 38.4839 39.9999 37.9367V9.61089Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
