/**
 * @file LabelBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-label-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M8 3C6.89543 3 6 3.89543 6 5V43.7285C6 45.2237 7.58093 46.1902 8.91178 45.5085L23.5441 38.0136C23.8304 37.867 24.1696 37.867 24.4559 38.0136L39.0882 45.5085C40.4191 46.1902 42 45.2237 42 43.7285V5C42 3.89543 41.1046 3 40 3H8ZM25 14C24.4477 14 24 14.4477 24 15V17C24 17.5523 24.4477 18 25 18H33C33.5523 18 34 17.5523 34 17V15C34 14.4477 33.5523 14 33 14H25Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
