/**
 * @file LayoutBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-layout-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M10 18V10H18V18H10ZM6 8C6 6.89543 6.89543 6 8 6H20C21.1046 6 22 6.89543 22 8V20C22 21.1046 21.1046 22 20 22H8C6.89543 22 6 21.1046 6 20V8ZM10 38V30H18V38H10ZM6 28C6 26.8954 6.89543 26 8 26H20C21.1046 26 22 26.8954 22 28V40C22 41.1046 21.1046 42 20 42H8C6.89543 42 6 41.1046 6 40V28ZM26 18C26 17.4477 26.4477 17 27 17H41C41.5523 17 42 17.4477 42 18V20C42 20.5523 41.5523 21 41 21H27C26.4477 21 26 20.5523 26 20V18ZM27 37C26.4477 37 26 37.4477 26 38V40C26 40.5523 26.4477 41 27 41H41C41.5523 41 42 40.5523 42 40V38C42 37.4477 41.5523 37 41 37H27ZM26 8C26 7.44772 26.4477 7 27 7H41C41.5523 7 42 7.44772 42 8V10C42 10.5523 41.5523 11 41 11H27C26.4477 11 26 10.5523 26 10V8ZM27 27C26.4477 27 26 27.4477 26 28V30C26 30.5523 26.4477 31 27 31H41C41.5523 31 42 30.5523 42 30V28C42 27.4477 41.5523 27 41 27H27Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
