/**
 * @file LeftBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-left-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M9.50521 11.9952L10.0004 12.4899L10.9899 11.4996L10.4948 11.0048L9.50521 11.9952ZM6.5 8.00258L6.00485 7.50779L5.51005 8.00294L6.00521 8.49774L6.5 8.00258ZM10.4952 4.99479L10.9899 4.49963L9.99963 3.51005L9.50484 4.00521L10.4952 4.99479ZM10.4948 11.0048L6.9948 7.50742L6.00521 8.49774L9.50521 11.9952L10.4948 11.0048ZM6.99516 8.49737L10.4952 4.99479L9.50484 4.00521L6.00485 7.50779L6.99516 8.49737Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
