/**
 * @file PieChartBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-pie-chart-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M40.9711 25C40.4535 33.9234 33.0531 41 24 41C14.6112 41 7 33.3888 7 24C7 14.9469 14.0766 7.54654 23 7.02892V25H40.9711ZM40.7361 21H27V7.26387C33.9842 8.50741 39.4926 14.0158 40.7361 21ZM24 45C35.598 45 45 35.598 45 24C45 12.402 35.598 3 24 3C12.402 3 3 12.402 3 24C3 35.598 12.402 45 24 45Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
