/**
 * @file PlayBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-play-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M38.6827 20.587C41.2347 22.1468 41.2347 25.8532 38.6827 27.413L14.086 42.4468C11.4206 44.0759 8 42.1577 8 39.0338V8.96617C8 5.84232 11.4206 3.92408 14.0861 5.55321L38.6827 20.587Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
