/**
 * @file RefreshBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-refresh-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M11 24C11 16.8203 16.8203 11 24 11C28.3528 11 32.2101 13.1404 34.5704 16.4296L31.7072 19.2929C31.0772 19.9229 31.5234 21 32.4143 21H42C42.5523 21 43 20.5523 43 20V10.4142C43 9.52333 41.9229 9.07716 41.2929 9.70713L38.8511 12.1489C35.3709 7.79269 30.0136 5 24 5C13.5066 5 5.00002 13.5066 5.00002 24H11ZM5 37.5858C5 38.4767 6.07714 38.9228 6.70711 38.2929L9.14894 35.851C12.6292 40.2073 17.9865 43 24 43C34.4935 43 43 34.4934 43 24H37C37 31.1797 31.1797 37 24 37C19.6473 37 15.79 34.8596 13.4296 31.5704L16.2929 28.7071C16.9229 28.0771 16.4767 27 15.5858 27H6C5.44772 27 5 27.4477 5 28V37.5858Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
