/**
 * @file ScanBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../interface";

export default Vue.extend({
    name: "icon-scan-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M43 30L40 30.0004L39 30.0005V36V39H36H12H9V36V33.0047V30.0047H8H6H5V33.0047V41C5 42.1046 5.89543 43 7 43H41C42.1046 43 43 42.1046 43 41V33V30ZM9 9V12V15V18H8H6H5V15V7C5 5.89543 5.89543 5 7 5H41C42.1046 5 43 5.89543 43 7V15V18H42H40H39V15V12V9H36H12H9ZM6 22C5.44772 22 5 22.4477 5 23V25C5 25.5523 5.44772 26 6 26H42C42.5523 26 43 25.5523 43 25V23C43 22.4477 42.5523 22 42 22H6Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
