/**
 * @file SubmitFormBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-submit-form-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M6.24609 7.5C6.24609 5.84315 7.58924 4.5 9.24609 4.5H34.7461C36.4029 4.5 37.7461 5.84315 37.7461 7.5V28.6247C37.2406 28.896 36.7658 29.2449 36.3393 29.6714L31.4961 34.5146L31.153 34.1714C28.8098 31.8283 25.0108 31.8283 22.6677 34.1714C20.3246 36.5146 20.3246 40.3136 22.6677 42.6567L23.511 43.5H9.24609C7.58924 43.5 6.24609 42.1569 6.24609 40.5V7.5ZM33.8244 43.5H29.1679L25.4961 39.8283C24.7151 39.0472 24.7151 37.7809 25.4961 36.9998C26.2772 36.2188 27.5435 36.2188 28.3246 36.9999L31.4961 40.1714L37.7461 33.9215V39.5783L33.8244 43.5ZM30.2461 15H13.7461V18H30.2461V15ZM22.7461 23.25H13.7461V26.25H22.7461V23.25Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M43.4103 33.9142L31.4961 45.8284L24.0819 38.4142L26.9103 35.5858L31.4961 40.1714L40.5819 31.0858L43.4103 33.9142Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
