/**
 * @file SwitchBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-switch-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M6.12976 28.9999H42.1298L42.1984 29C42.9111 29 43.268 29.8617 42.7641 30.3657L33.4573 39.6724C33.0935 40.0363 32.5129 40.0646 32.1154 39.738L30.8469 38.6958C30.3922 38.3223 30.3568 37.6389 30.7703 37.2203L34.9397 32.9999H6.12976C5.57748 32.9999 5.12976 32.5522 5.12976 31.9999V29.9999C5.12976 29.4477 5.57748 28.9999 6.12976 28.9999ZM42 15H13.2401L17.5799 10.6623C18.0237 10.2187 17.954 9.48068 17.435 9.12796L15.9979 8.15126C15.6009 7.88144 15.0682 7.93179 14.7287 8.27123L5.36568 17.6343C4.86171 18.1382 5.21864 19 5.93137 19H6.00003L6 19H42C42.5523 19 43 18.5523 43 18V16C43 15.4477 42.5523 15 42 15Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
