/**
 * @file TelephoneBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-telephone-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 50,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 50 50"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g opacity="0.01">
                    <rect
                        x="2.5"
                        y="2.5"
                        width="45"
                        height="45"
                        rx="1.5"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="3"
                    />
                    <path
                        opacity="0.2"
                        d="M25 11.5C32.4558 11.5 38.5 17.5442 38.5 25C38.5 32.4558 32.4558 38.5 25 38.5C17.5442 38.5 11.5 32.4558 11.5 25C11.5 17.5442 17.5442 11.5 25 11.5Z"
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M25 15.5C30.2467 15.5 34.5 19.7533 34.5 25C34.5 30.2467 30.2467 34.5 25 34.5C19.7533 34.5 15.5 30.2467 15.5 25C15.5 19.7533 19.7533 15.5 25 15.5Z"
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M1 25H49"
                        stroke={props.color}
                        stroke-width="3"
                    />
                    <path
                        opacity="0.2"
                        d="M25 49L25 1"
                        stroke={props.color}
                        stroke-width="3"
                    />
                    <path
                        opacity="0.2"
                        d="M2.5 47.5L47.5 2.5"
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M47.5 47.5L2.5 2.5"
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        d="M8.5 41L8.5 9C8.5 7.61929 9.61929 6.5 11 6.5H39C40.3807 6.5 41.5 7.61929 41.5 9V41C41.5 42.3807 40.3807 43.5 39 43.5H11C9.61929 43.5 8.5 42.3807 8.5 41Z"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        d="M6.5 39V11C6.5 9.61929 7.61929 8.5 9 8.5H41C42.3807 8.5 43.5 9.61929 43.5 11V39C43.5 40.3807 42.3807 41.5 41 41.5H9C7.61929 41.5 6.5 40.3807 6.5 39Z"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        d="M7.5 40.2V9.8C7.5 8.52974 8.52974 7.5 9.8 7.5H40.2C41.4703 7.5 42.5 8.52974 42.5 9.8V40.2C42.5 41.4703 41.4703 42.5 40.2 42.5H9.8C8.52974 42.5 7.5 41.4703 7.5 40.2Z"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                    <path
                        d="M25 6.5C35.2173 6.5 43.5 14.7827 43.5 25C43.5 35.2173 35.2173 43.5 25 43.5C14.7827 43.5 6.5 35.2173 6.5 25C6.5 14.7827 14.7827 6.5 25 6.5Z"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="3"
                        stroke-linecap="square"
                    />
                </g>
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M29.0936 31.3908L32.112 28.3724C32.4741 28.0103 33.0617 28.0108 33.4238 28.3729L40.3693 35.3184C40.7314 35.6805 40.7328 36.2673 40.3707 36.6294L37.3974 39.6027C35.0413 41.9588 25.0495 39.5935 17.7566 32.3005C10.4636 25.0076 8.06083 15.0533 10.4544 12.6597L13.4277 9.68639C13.7898 9.32428 14.3761 9.32516 14.7382 9.68727L21.6847 16.6338C22.0468 16.9959 22.0468 17.583 21.6847 17.9451L18.6663 20.9635C18.6663 20.9635 17.7566 23.7278 22.0429 28.0142C26.3293 32.3005 29.0936 31.3908 29.0936 31.3908ZM27.5972 27.2304L29.2836 25.544C31.2106 23.6169 34.3309 23.6231 36.2522 25.5445L43.1978 32.49C45.1144 34.4066 45.1309 37.5261 43.1991 39.4578L40.2258 42.4311C38.4862 44.1708 36.0563 44.4867 34.3474 44.4813C32.4386 44.4752 30.3163 44.0672 28.1877 43.3727C23.9162 41.9792 19.0424 39.2433 14.9281 35.129C10.8189 31.0198 8.07232 26.1589 6.67219 21.8893C5.97451 19.7617 5.56364 17.6366 5.56001 15.7204C5.55674 13.9923 5.88625 11.571 7.62597 9.8313L10.5993 6.85797C12.5285 4.92881 15.6473 4.93959 17.5666 6.85885L24.5131 13.8054C26.4374 15.7296 26.4374 18.8493 24.5131 20.7736L22.8267 22.46C23.0907 23.043 23.6561 23.9704 24.8714 25.1857C26.0867 26.401 27.0141 26.9664 27.5972 27.2304ZM28.3925 27.4716C28.3925 27.4716 28.3916 27.4716 28.3898 27.4716C28.3916 27.4715 28.3925 27.4716 28.3925 27.4716ZM22.5855 21.6646C22.5855 21.6646 22.5856 21.6655 22.5856 21.6673C22.5855 21.6655 22.5855 21.6646 22.5855 21.6646Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
