/**
 * @file UrgentBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue, { CreateElement, VNode } from "vue";
import { IIconProps } from "../type";

export default Vue.extend({
    name: "icon-urgent-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    data() {
        return {};
    },
    render(h: CreateElement): VNode {
        const props: IIconProps = {
            size: this.size,
            color: this.color,
        };
        return (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M40.6133 21C40.6133 13.5333 35.4987 7.26122 28.5818 5.49601C28.334 3.52479 26.6517 2 24.6133 2C22.5748 2 20.8925 3.52479 20.6447 5.49601C13.7279 7.26122 8.61328 13.5333 8.61328 21V33L6.19907 35.4142C5.82399 35.7893 5.61328 36.298 5.61328 36.8284V39C5.61328 39.5523 6.061 40 6.61328 40H19.6133C19.6133 42.7614 21.8519 45 24.6133 45C27.3747 45 29.6133 42.7614 29.6133 40H42.6133C43.1656 40 43.6133 39.5523 43.6133 39V36.8284C43.6133 36.298 43.4026 35.7893 43.0275 35.4142L40.6133 33V21ZM24.6133 21H31.6133L24.6133 33V25H17.6133L24.6133 13V21Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
