/**
 * 基础图标
 * **/
import React from 'react';
import TableList, { IconItem } from './index';

import {
	MenuBaseOutline,
	MoreBaseOutline,
	BackBaseOutline,
	CloseBaseOutline,
	SubmitBaseOutline,
	SearchBaseOutline,
	ServiceBaseOutline,
	NewsBaseOutline,
	ShoppingBagBaseOutline,
	CameraBaseOutline,
	RecordingBaseOutline,
	ImageBaseOutline,
	AddBaseOutline,
	RefreshBaseOutline,
	FlashOnBaseOutline,
	FlashOffBaseOutline,
	WandBaseOutline,
	CopyBaseOutline,
	DeleteBaseOutline,
	LinkBaseOutline,
	PlayBaseOutline,
	TextBaseOutline,
	PlayButtonBaseOutline,
	TextButtonBaseOutline,
	PauseBaseOutline,
	UploadBaseOutline,
	DownloadBaseOutline,
	SwitchBaseOutline,
	UndoBaseOutline,
	JumpPageBaseOutline,
	ScreenBaseOutline,
	TreeBaseOutline,
	FormBaseOutline,
	SubmitFormBaseOutline,
	EditFormBaseOutline,
	MailBaseOutline,
	PkBaseOutline,
	AdjustBaseOutline,
	LocationBaseOutline,
	ShoppingCartBaseOutline,
	GiftBaseOutline,
	FlagBaseOutline,
	ScanBaseOutline,
	FlashlightBaseOutline,
	EditBaseOutline,
	ArticleBaseOutline,
	DirectoryBaseOutline,
	TemplateBaseOutline,
	ClockBaseOutline,
	AlarmBaseOutline,
	InformationBaseOutline,
	AddNewBaseOutline,
	ClueBaseOutline,
	LabelBaseOutline,
	UninterestedBaseOutline,
	WifilBaseOutline,
	VisiblelBaseOutline,
	InvisiblelBaseOutline,
	CameraSwitchinglBaseOutline,
	PhotoAlbumlBaseOutline,
	SuccesslBaseOutline,
	FaillBaseOutline,
	WarnBaseOutline,
	HelpBaseOutline,
	NoticeBaseOutline,
	ExchangeBaseOutline,
	SmileBaseOutline,
	MicrophoneBaseOutline,
	RepairBaseOutline,
	TelephoneBaseOutline,
	ShareBaseOutline,
	SettingsBaseOutline,
	TrophyBaseOutline,
	DiscountBaseOutline,
	DiscoverBaseOutline,
	ReportBaseOutline,
	FemaleBaseOutline,
	MaleBaseOutline,
	LikeBaseOutline,
	CollectionBaseOutline,
	WechatBaseOutline,
	QualityBaseOutline,
	SettlementBaseOutline,
	CalendarBaseOutline,
	PieChartBaseOutline,
	CopperBaseOutline,
	UrgentBaseOutline,
	BackToTopBaseOutline,
	QrCodeBaseOutline,
	LayoutBaseOutline,
	CreditCardBaseOutline,
	OthersBaseOutline,
	CouponBaseOutline,
	HomepageBaseOutline,
	WalletBaseOutline,
	CatalogueBaseOutline,

	MenuBaseFilled,
	MoreBaseFilled,
	BackBaseFilled,
	CloseBaseFilled,
	SubmitBaseFilled,
	SearchBaseFilled,
	ServiceBaseFilled,
	NewsBaseFilled,
	ShoppingBagBaseFilled,
	CameraBaseFilled,
	RecordingBaseFilled,
	ImageBaseFilled,
	AddBaseFilled,
	RefreshBaseFilled,
	FlashOnBaseFilled,
	FlashOffBaseFilled,
	WandBaseFilled,
	CopyBaseFilled,
	DeleteBaseFilled,
	LinkBaseFilled,
	PlayBaseFilled,
	TextBaseFilled,
	PlayButtonBaseFilled,
	TextButtonBaseFilled,
	PauseBaseFilled,
	UploadBaseFilled,
	DownloadBaseFilled,
	SwitchBaseFilled,
	UndoBaseFilled,
	JumpPageBaseFilled,
	ScreenBaseFilled,
	TreeBaseFilled,
	FormBaseFilled,
	SubmitFormBaseFilled,
	EditFormBaseFilled,
	MailBaseFilled,
	PkBaseFilled,
	AdjustBaseFilled,
	LocationBaseFilled,
	ShoppingCartBaseFilled,
	GiftBaseFilled,
	FlagBaseFilled,
	ScanBaseFilled,
	FlashlightBaseFilled,
	EditBaseFilled,
	ArticleBaseFilled,
	DirectoryBaseFilled,
	TemplateBaseFilled,
	ClockBaseFilled,
	AlarmBaseFilled,
	InformationBaseFilled,
	AddNewBaseFilled,
	ClueBaseFilled,
	LabelBaseFilled,
	UninterestedBaseFilled,
	WifilBaseFilled,
	VisiblelBaseFilled,
	InvisiblelBaseFilled,
	CameraSwitchinglBaseFilled,
	PhotoAlbumlBaseFilled,
	SuccessBaseFilled,
	FailBaseFilled,
	WarnBaseFilled,
	HelpBaseFilled,
	NoticeBaseFilled,
	ExchangeBaseFilled,
	SmileBaseFilled,
	MicrophoneBaseFilled,
	RepairBaseFilled,
	TelephoneBaseFilled,
	ShareBaseFilled,
	SettingsBaseFilled,
	TrophyBaseFilled,
	DiscountBaseFilled,
	DiscoverBaseFilled,
	ReportBaseFilled,
	FemaleBaseFilled,
	MaleBaseFilled,
	LikeBaseFilled,
	CollectionBaseFilled,
	WechatBaseFilled,
	QualityBaseFilled,
	SettlementBaseFilled,
	CalendarBaseFilled,
	PieChartBaseFilled,
	CopperBaseFilled,
	UrgentBaseFilled,
	BackToTopBaseFilled,
	QrCodeBaseFilled,
	LayoutBaseFilled,
	OthersBaseFilled,
	CouponBaseFilled,
	HomepageBaseFilled,
	WalletBaseFilled,
	CreditCardBaseFilled,
	CataloguelBaseFilled,
} from '@icon-garden/react';

const outlined: IconItem[] = [
	{ name: 'menu-base-outline', title: '菜单导航', icon: MenuBaseOutline },
	{ name: 'more-base-outline', title: '更多', icon: MoreBaseOutline },
	{ name: 'back-base-outline', title: '返回', icon: BackBaseOutline },
	{ name: 'close-base-outline', title: '关闭', icon: CloseBaseOutline },
	{ name: 'submit-base-outline', title: '完成提交', icon: SubmitBaseOutline },
	{ name: 'search-base-outline', title: '查询搜索', icon: SearchBaseOutline },
	{ name: 'service-base-outline', title: '耳麦客服', icon: ServiceBaseOutline },
	{ name: 'news-base-outline', title: '消息对话', icon: NewsBaseOutline },
	{ name: 'shopping-bag-base-outline', title: '购物袋', icon: ShoppingBagBaseOutline },
	{ name: 'camera-base-outline', title: '相机拍照', icon: CameraBaseOutline },
	{ name: 'recording-base-outline', title: '摄影录像', icon: RecordingBaseOutline },
	{ name: 'image-base-outline', title: '图片照片', icon: ImageBaseOutline },
	{ name: 'add-base-outline', title: '新建添加', icon: AddBaseOutline },
	{ name: 'refresh-base-outline', title: '同步更新刷新', icon: RefreshBaseOutline },
	{ name: 'flash-on-base-outline', title: '启用闪光灯', icon: FlashOnBaseOutline },
	{ name: 'flash-off-base-outline', title: '禁用闪光灯', icon: FlashOffBaseOutline },
	{ name: 'wand-base-outline', title: '魔棒', icon: WandBaseOutline },
	{ name: 'copy-base-outline', title: '复制', icon: CopyBaseOutline },
	{ name: 'delete-base-outline', title: '删除', icon: DeleteBaseOutline },
	{ name: 'link-base-outline', title: '链接', icon: LinkBaseOutline },
	{ name: 'play-base-outline', title: '播放', icon: PlayBaseOutline },
	{ name: 'text-base-outline', title: '文字', icon: TextBaseOutline },
	{ name: 'play-button-base-outline', title: '播放按钮', icon: PlayButtonBaseOutline },
	{ name: 'text-button-base-outline', title: '文字按钮', icon: TextButtonBaseOutline },
	{ name: 'pause-base-outline', title: '暂停', icon: PauseBaseOutline },
	{ name: 'upload-base-outline', title: '上传', icon: UploadBaseOutline },
	{ name: 'download-base-outline', title: '下载', icon: DownloadBaseOutline },
	{ name: 'switch-base-outline', title: '切换', icon: SwitchBaseOutline },
	{ name: 'undo-base-outline', title: '撤销', icon: UndoBaseOutline },
	{ name: 'jump-page-base-outline', title: '跳转链接', icon: JumpPageBaseOutline },
	{ name: 'screen-base-outline', title: '筛选', icon: ScreenBaseOutline },
	{ name: 'tree-base-outline', title: '组织结构树', icon: TreeBaseOutline },
	{ name: 'form-base-outline', title: '表单订单', icon: FormBaseOutline },
	{ name: 'submit-form-base-outline', title: '完成表单订单', icon: SubmitFormBaseOutline },
	{ name: 'edit-form-base-outline', title: '编辑表单订单', icon: EditFormBaseOutline },
	{ name: 'mail-base-outline', title: '邮件', icon: MailBaseOutline },
	{ name: 'pk-base-outline', title: '比较', icon: PkBaseOutline },
	{ name: 'adjust-base-outline', title: '配置', icon: AdjustBaseOutline },
	{ name: 'location-base-outline', title: '定位本地', icon: LocationBaseOutline },
	{ name: 'shopping-cart-base-outline', title: '购物车', icon: ShoppingCartBaseOutline },
	{ name: 'gift-base-outline', title: '礼物', icon: GiftBaseOutline },
	{ name: 'flag-base-outline', title: '旗帜标记', icon: FlagBaseOutline },
	{ name: 'scan-base-outline', title: '扫一扫', icon: ScanBaseOutline },
	{ name: 'flashlight-base-outline', title: '手电筒', icon: FlashlightBaseOutline },
	{ name: 'edit-base-outline', title: '编辑编写', icon: EditBaseOutline },
	{ name: 'article-base-outline', title: '文章新闻', icon: ArticleBaseOutline },
	{ name: 'directory-base-outline', title: '通讯录', icon: DirectoryBaseOutline },
	{ name: 'template-base-outline', title: '模版', icon: TemplateBaseOutline },
	{ name: 'clock-base-outline', title: '时钟', icon: ClockBaseOutline },
	{ name: 'alarm-base-outline', title: '闹钟', icon: AlarmBaseOutline },
	{ name: 'information-base-outline', title: '提示', icon: InformationBaseOutline },
	{ name: 'add-new-base-outline', title: '添加', icon: AddNewBaseOutline },
	{ name: 'clue-base-outline', title: '线索', icon: ClueBaseOutline },
	{ name: 'label-base-outline', title: '标签', icon: LabelBaseOutline },
	{ name: 'uninterested-base-outline', title: '不感兴趣', icon: UninterestedBaseOutline },
	{ name: 'wifil-base-outline', title: 'wifi', icon: WifilBaseOutline },
	{ name: 'visiblel-base-outline', title: '可见', icon: VisiblelBaseOutline },
	{ name: 'invisiblel-base-outline', title: '不可见', icon: InvisiblelBaseOutline },
	{ name: 'camera-switchingl-base-outline', title: '摄像头翻转', icon: CameraSwitchinglBaseOutline },
	{ name: 'photo-albuml-base-outline', title: '相册图集', icon: PhotoAlbumlBaseOutline },
	{ name: 'successl-base-outline', title: '成功', icon: SuccesslBaseOutline },
	{ name: 'faill-base-outline', title: '失败', icon: FaillBaseOutline },
	{ name: 'warn-base-outline', title: '提醒', icon: WarnBaseOutline },
	{ name: 'help-base-outline', title: '帮助', icon: HelpBaseOutline },
	{ name: 'notice-base-outline', title: '通知', icon: NoticeBaseOutline },
	{ name: 'exchange-base-outline', title: '交换', icon: ExchangeBaseOutline },
	{ name: 'smile-base-outline', title: '服务', icon: SmileBaseOutline },
	{ name: 'microphone-base-outline', title: '话筒', icon: MicrophoneBaseOutline },
	{ name: 'repair-base-outline', title: '维修', icon: RepairBaseOutline },
	{ name: 'telephone-base-outline', title: '电话', icon: TelephoneBaseOutline },
	{ name: 'share-base-outline', title: '分享', icon: ShareBaseOutline },
	{ name: 'settings-base-outline', title: '设置', icon: SettingsBaseOutline },
	{ name: 'trophy-base-outline', title: '奖杯', icon: TrophyBaseOutline },
	{ name: 'discount-base-outline', title: '折扣', icon: DiscountBaseOutline },
	{ name: 'discover-base-outline', title: '发现', icon: DiscoverBaseOutline },
	{ name: 'report-base-outline', title: '报表', icon: ReportBaseOutline },
	{ name: 'female-base-outline', title: '女性', icon: FemaleBaseOutline },
	{ name: 'male-base-outline', title: '男性', icon: MaleBaseOutline },
	{ name: 'like-base-outline', title: '喜欢', icon: LikeBaseOutline },
	{ name: 'collection-base-outline', title: '收藏', icon: CollectionBaseOutline },
	{ name: 'wechat-base-outline', title: '微信', icon: WechatBaseOutline },
	{ name: 'quality-base-outline', title: '星级', icon: QualityBaseOutline },
	{ name: 'settlement-base-outline', title: '结算', icon: SettlementBaseOutline },
	{ name: 'calendar-base-outline', title: '日历', icon: CalendarBaseOutline },
	{ name: 'pie-chart-base-outline', title: '饼图', icon: PieChartBaseOutline },
	{ name: 'copper-base-outline', title: '铜钱', icon: CopperBaseOutline },
	{ name: 'urgent-base-outline', title: '急求', icon: UrgentBaseOutline },
	{ name: 'back-to-top-base-outline', title: '返回顶部', icon: BackToTopBaseOutline },
	{ name: 'qr-code-base-outline', title: '二维码', icon: QrCodeBaseOutline },
	{ name: 'layout-base-outline', title: '布局', icon: LayoutBaseOutline },
	{ name: 'credit-card-base-outline', title: '信用卡', icon: CreditCardBaseOutline },
	{ name: 'others-base-outline', title: '其他', icon: OthersBaseOutline },
	{ name: 'coupon-base-outline', title: '卡券', icon: CouponBaseOutline },
	{ name: 'homepage-base-outline', title: '首页', icon: HomepageBaseOutline },
	{ name: 'wallet-base-outline', title: '钱包', icon: WalletBaseOutline },
	{ name: 'catalogue-base-outline', title: '目录', icon: CatalogueBaseOutline },
];

const filled: IconItem[] = [
	{ name: 'menu-base-filled', title: '菜单导航', icon: MenuBaseFilled },
	{ name: 'more-base-filled', title: '更多', icon: MoreBaseFilled },
	{ name: 'back-base-filled', title: '返回', icon: BackBaseFilled },
	{ name: 'close-base-filled', title: '关闭', icon: CloseBaseFilled },
	{ name: 'submit-base-filled', title: '完成提交', icon: SubmitBaseFilled },
	{ name: 'search-base-filled', title: '查询搜索', icon: SearchBaseFilled },
	{ name: 'service-base-filled', title: '耳麦客服', icon: ServiceBaseFilled },
	{ name: 'news-base-filled', title: '消息对话', icon: NewsBaseFilled },
	{ name: 'shopping-bag-base-filled', title: '购物袋', icon: ShoppingBagBaseFilled },
	{ name: 'camera-base-filled', title: '相机拍照', icon: CameraBaseFilled },
	{ name: 'recording-base-filled', title: '摄影录像', icon: RecordingBaseFilled },
	{ name: 'image-base-filled', title: '图片照片', icon: ImageBaseFilled },
	{ name: 'add-base-filled', title: '新建添加', icon: AddBaseFilled },
	{ name: 'refresh-base-filled', title: '同步更新刷新', icon: RefreshBaseFilled },
	{ name: 'flash-on-base-filled', title: '启用闪光灯', icon: FlashOnBaseFilled },
	{ name: 'flash-off-base-filled', title: '禁用闪光灯', icon: FlashOffBaseFilled },
	{ name: 'wand-base-filled', title: '魔棒', icon: WandBaseFilled },
	{ name: 'copy-base-filled', title: '复制', icon: CopyBaseFilled },
	{ name: 'delete-base-filled', title: '删除', icon: DeleteBaseFilled },
	{ name: 'link-base-filled', title: '链接', icon: LinkBaseFilled },
	{ name: 'play-base-filled', title: '播放', icon: PlayBaseFilled },
	{ name: 'text-base-filled', title: '文字', icon: TextBaseFilled },
	{ name: 'play-button-base-filled', title: '播放按钮', icon: PlayButtonBaseFilled },
	{ name: 'text-button-base-filled', title: '文字按钮', icon: TextButtonBaseFilled },
	{ name: 'pause-base-filled', title: '暂停', icon: PauseBaseFilled },
	{ name: 'upload-base-filled', title: '上传', icon: UploadBaseFilled },
	{ name: 'download-base-filled', title: '下载', icon: DownloadBaseFilled },
	{ name: 'switch-base-filled', title: '切换', icon: SwitchBaseFilled },
	{ name: 'undo-base-filled', title: '撤销', icon: UndoBaseFilled },
	{ name: 'jump-page-base-filled', title: '跳转链接', icon: JumpPageBaseFilled },
	{ name: 'screen-base-filled', title: '筛选', icon: ScreenBaseFilled },
	{ name: 'tree-base-filled', title: '组织结构树', icon: TreeBaseFilled },
	{ name: 'form-base-filled', title: '表单订单', icon: FormBaseFilled },
	{ name: 'submit-form-base-filled', title: '完成表单订单', icon: SubmitFormBaseFilled },
	{ name: 'edit-form-base-filled', title: '编辑表单订单', icon: EditFormBaseFilled },
	{ name: 'mail-base-filled', title: '邮件', icon: MailBaseFilled },
	{ name: 'pk-base-filled', title: '比较', icon: PkBaseFilled },
	{ name: 'adjust-base-filled', title: '配置', icon: AdjustBaseFilled },
	{ name: 'location-base-filled', title: '定位本地', icon: LocationBaseFilled },
	{ name: 'shopping-cart-base-filled', title: '购物车', icon: ShoppingCartBaseFilled },
	{ name: 'gift-base-filled', title: '礼物', icon: GiftBaseFilled },
	{ name: 'flag-base-filled', title: '旗帜标记', icon: FlagBaseFilled },
	{ name: 'scan-base-filled', title: '扫一扫', icon: ScanBaseFilled },
	{ name: 'flashlight-base-filled', title: '手电筒', icon: FlashlightBaseFilled },
	{ name: 'edit-base-filled', title: '编辑编写', icon: EditBaseFilled },
	{ name: 'article-base-filled', title: '文章新闻', icon: ArticleBaseFilled },
	{ name: 'directory-base-filled', title: '通讯录', icon: DirectoryBaseFilled },
	{ name: 'template-base-filled', title: '模版', icon: TemplateBaseFilled },
	{ name: 'clock-base-filled', title: '时钟', icon: ClockBaseFilled },
	{ name: 'alarm-base-filled', title: '闹钟', icon: AlarmBaseFilled },
	{ name: 'information-base-filled', title: '提示', icon: InformationBaseFilled },
	{ name: 'add-new-base-filled', title: '添加', icon: AddNewBaseFilled },
	{ name: 'clue-base-filled', title: '线索', icon: ClueBaseFilled },
	{ name: 'label-base-filled', title: '标签', icon: LabelBaseFilled },
	{ name: 'uninterested-base-filled', title: '不感兴趣', icon: UninterestedBaseFilled },
	{ name: 'wifil-base-filled', title: 'wifi', icon: WifilBaseFilled },
	{ name: 'visiblel-base-filled', title: '可见', icon: VisiblelBaseFilled },
	{ name: 'invisiblel-base-filled', title: '不可见', icon: InvisiblelBaseFilled },
	{ name: 'camera-switchingl-base-filled', title: '摄像头翻转', icon: CameraSwitchinglBaseFilled },
	{ name: 'photo-albuml-base-filled', title: '相册图集', icon: PhotoAlbumlBaseFilled },
	{ name: 'success-base-filled', title: '成功', icon: SuccessBaseFilled },
	{ name: 'fail-base-filled', title: '失败', icon: FailBaseFilled },
	{ name: 'warn-base-filled', title: '提醒', icon: WarnBaseFilled },
	{ name: 'help-base-filled', title: '帮助', icon: HelpBaseFilled },
	{ name: 'notice-base-filled', title: '通知', icon: NoticeBaseFilled },
	{ name: 'exchange-base-filled', title: '交换', icon: ExchangeBaseFilled },
	{ name: 'smile-base-filled', title: '服务', icon: SmileBaseFilled },
	{ name: 'microphone-base-filled', title: '话筒', icon: MicrophoneBaseFilled },
	{ name: 'repair-base-filled', title: '维修', icon: RepairBaseFilled },
	{ name: 'telephone-base-filled', title: '电话', icon: TelephoneBaseFilled },
	{ name: 'share-base-filled', title: '分享', icon: ShareBaseFilled },
	{ name: 'settings-base-filled', title: '设置', icon: SettingsBaseFilled },
	{ name: 'trophy-base-filled', title: '奖杯', icon: TrophyBaseFilled },
	{ name: 'discount-base-filled', title: '折扣', icon: DiscountBaseFilled },
	{ name: 'discover-base-filled', title: '发现', icon: DiscoverBaseFilled },
	{ name: 'report-base-filled', title: '报表', icon: ReportBaseFilled },
	{ name: 'female-base-filled', title: '女性', icon: FemaleBaseFilled },
	{ name: 'male-base-filled', title: '男性', icon: MaleBaseFilled },
	{ name: 'like-base-filled', title: '喜欢', icon: LikeBaseFilled },
	{ name: 'collection-base-filled', title: '收藏', icon: CollectionBaseFilled },
	{ name: 'wechat-base-filled', title: '微信', icon: WechatBaseFilled },
	{ name: 'quality-base-filled', title: '星级', icon: QualityBaseFilled },
	{ name: 'settlement-base-filled', title: '结算', icon: SettlementBaseFilled },
	{ name: 'calendar-base-filled', title: '日历', icon: CalendarBaseFilled },
	{ name: 'pie-chart-base-filled', title: '饼图', icon: PieChartBaseFilled },
	{ name: 'copper-base-filled', title: '铜钱', icon: CopperBaseFilled },
	{ name: 'urgent-base-filled', title: '急求', icon: UrgentBaseFilled },
	{ name: 'back-to-top-base-filled', title: '返回顶部', icon: BackToTopBaseFilled },
	{ name: 'qr-code-base-filled', title: '二维码', icon: QrCodeBaseFilled },
	{ name: 'layout-base-filled', title: '布局', icon: LayoutBaseFilled },
	{ name: 'others-base-filled', title: '其他', icon: OthersBaseFilled },
	{ name: 'coupon-base-filled', title: '卡券', icon: CouponBaseFilled },
	{ name: 'homepage-base-filled', title: '首页', icon: HomepageBaseFilled },
	{ name: 'wallet-base-filled', title: '钱包', icon: WalletBaseFilled },
	{ name: 'credit-card-base-filled', title: '信用卡', icon: CreditCardBaseFilled },
	{ name: 'cataloguel-base-filled', title: '目录', icon: CataloguelBaseFilled },
];

export default () => {
	return <TableList outlined={outlined} filled={filled} />
}