
/**
 * @author Auto Generated by IconGarden
 */

import React from 'react';
import { IIconProps } from '../type';

export default ({
  size = 48,
  color = "black",
  ...extra
}: IIconProps) => (
  <svg {...extra} width={size} height={size} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M44 24V9H24H4V24V39H24" stroke={color} stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M44 34L30 34" stroke={color} stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M35 29L30 34L35 39" stroke={color} stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M4 9L24 24L44 9" stroke={color} stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

);
