/**
 * @file AdjustBaseOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M25 11C25 8.79086 26.7909 7 29 7H33C35.2091 7 37 8.79086 37 11V12H44C44.5523 12 45 12.4477 45 13V15C45 15.5523 44.5523 16 44 16H37V17C37 19.2091 35.2091 21 33 21H29C26.7909 21 25 19.2091 25 17V16H4C3.44772 16 3 15.5523 3 15V13C3 12.4477 3.44772 12 4 12H25V11ZM33 11H29V17H33V11ZM11 30C11 27.7909 12.7909 26 15 26H19C21.2091 26 23 27.7909 23 30V31H44C44.5523 31 45 31.4477 45 32V34C45 34.5523 44.5523 35 44 35H23V36C23 38.2091 21.2091 40 19 40H15C12.7909 40 11 38.2091 11 36V35H4C3.44771 35 3 34.5523 3 34V32C3 31.4477 3.44772 31 4 31H11V30ZM19 30H15V36H19V30Z"
            fill={color}
        />
    </svg>
);
