/**
 * @file BackBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            d="M24.3848 5.61523L6.70711 23.2929C6.31658 23.6834 6.31658 24.3166 6.70711 24.7071L24.3848 42.3848"
            stroke={color}
            stroke-width="6"
        />
    </svg>
);
