/**
 * @file DeleteBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M17 2C16.4477 2 16 2.44772 16 3V5C16 5.55228 16.4477 6 17 6H31C31.5523 6 32 5.55228 32 5V3C32 2.44772 31.5523 2 31 2H17ZM6 10C6 9.44772 6.44772 9 7 9H9H39H41C41.5523 9 42 9.44772 42 10V12C42 12.5523 41.5523 13 41 13H39V41C39 43.2091 37.2091 45 35 45H13C10.7909 45 9 43.2091 9 41V13H7C6.44772 13 6 12.5523 6 12V10ZM18 19C18 18.4477 18.4477 18 19 18H21C21.5523 18 22 18.4477 22 19V35C22 35.5523 21.5523 36 21 36H19C18.4477 36 18 35.5523 18 35V19ZM26 19C26 18.4477 26.4477 18 27 18H29C29.5523 18 30 18.4477 30 19V35C30 35.5523 29.5523 36 29 36H27C26.4477 36 26 35.5523 26 35V19Z"
            fill={color}
        />
    </svg>
);
