/**
 * @file EditBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M28.3345 5.18027C27.5535 4.39922 26.2872 4.39922 25.5061 5.18027L5.2929 25.3935C5.10536 25.581 5.00001 25.8354 5.00001 26.1006L5.00001 36.0001C5.00001 36.5524 5.44772 37.0001 6.00001 37.0001H15.8995C16.1647 37.0001 16.4191 36.8947 16.6066 36.7072L36.8198 16.494C37.6009 15.7129 37.6009 14.4466 36.8198 13.6656L28.3345 5.18027ZM6 40.0001C5.44772 40.0001 5 40.4478 5 41.0001V43.0001C5 43.5523 5.44772 44.0001 6 44.0001H42C42.5523 44.0001 43 43.5523 43 43.0001V41.0001C43 40.4478 42.5523 40.0001 42 40.0001H6Z"
            fill={color}
        />
    </svg>
);
