/**
 * @file FlagBaseOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M9 8V6H36.7756L33.8035 12.5073C33.0805 14.0904 33.0805 15.9096 33.8035 17.4927L36.7756 24H9V12V8ZM5 8V4C5 2.89543 5.89543 2 7 2H39.8878C41.344 2 42.312 3.50637 41.707 4.8309L37.442 14.1691C37.201 14.6968 37.201 15.3032 37.442 15.8309L41.707 25.1691C42.312 26.4936 41.344 28 39.8878 28H9V44C9 45.1046 8.10457 46 7 46C5.89543 46 5 45.1046 5 44V26V12V8Z"
            fill={color}
        />
    </svg>
);
