/**
 * @file FlashOffBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            d="M16.9927 7.45997C17.271 6.5902 18.0795 6 18.9928 6H33.0587C34.8144 6 35.795 8.02647 34.7053 9.40323L26.3188 20H31.61C33.4031 20 34.3715 22.1025 33.2057 23.4652L18.1591 41.0527C16.6009 42.8741 13.6668 41.2439 14.39 38.9588L18.1746 27H13.6168C12.194 27 11.1831 25.615 11.6167 24.26L16.9927 7.45997Z"
            fill={color}
        />
    </svg>
);
