/**
 * @file ForkBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <mask id="path-1-inside-1_2860_28230" fill={color}>
            <rect x="6" y="2" width="4" height="4" rx="0.8" />
        </mask>
        <rect
            x="6"
            y="2"
            width="4"
            height="4"
            rx="0.8"
            stroke={color}
            stroke-width="2"
            mask="url(#path-1-inside-1_2860_28230)"
        />
        <mask id="path-2-inside-2_2860_28230" fill={color}>
            <rect x="2" y="10" width="4" height="4" rx="0.8" />
        </mask>
        <rect
            x="2"
            y="10"
            width="4"
            height="4"
            rx="0.8"
            stroke={color}
            stroke-width="2"
            mask="url(#path-2-inside-2_2860_28230)"
        />
        <mask id="path-3-inside-3_2860_28230" fill={color}>
            <rect x="10" y="10" width="4" height="4" rx="0.8" />
        </mask>
        <rect
            x="10"
            y="10"
            width="4"
            height="4"
            rx="0.8"
            stroke={color}
            stroke-width="2"
            mask="url(#path-3-inside-3_2860_28230)"
        />
        <path
            d="M12 10V8.6C12 8.54477 11.9552 8.5 11.9 8.5H4.1C4.04477 8.5 4 8.54477 4 8.6V10"
            stroke={color}
        />
        <rect x="7.5" y="6" width="1" height="3" fill={color} />
    </svg>
);
