/**
 * @file LabelBaseOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M10 40.4569V7H38V40.4569L26.2795 34.4534C24.8482 33.7203 23.1518 33.7203 21.7205 34.4534L10 40.4569ZM6 5C6 3.89543 6.89543 3 8 3H40C41.1046 3 42 3.89543 42 5V43.7285C42 45.2237 40.4191 46.1902 39.0882 45.5085L24.4559 38.0136C24.1696 37.867 23.8304 37.867 23.5441 38.0136L8.91178 45.5085C7.58093 46.1902 6 45.2237 6 43.7285V5ZM25 14C24.4477 14 24 14.4477 24 15V17C24 17.5523 24.4477 18 25 18H33C33.5523 18 34 17.5523 34 17V15C34 14.4477 33.5523 14 33 14H25Z"
            fill={color}
        />
    </svg>
);
