/**
 * @file LeftSmallBaseFilledPc
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            d="M5.39043 8.31235C5.19027 8.15222 5.19027 7.84778 5.39043 7.68765L9.35012 4.5199C9.61203 4.31038 10 4.49685 10 4.83225L10 11.1677C10 11.5032 9.61203 11.6896 9.35012 11.4801L5.39043 8.31235Z"
            fill={color}
        />
    </svg>
);
