/**
 * @file LikeBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M25.4872 9.45081C30.0883 4.84973 37.5481 4.84973 42.1492 9.45081C46.5702 13.8718 46.7432 20.9322 42.6683 25.5598L25.4748 42.8947C24.6943 43.6816 23.4227 43.6838 22.6396 42.8995L5.38778 25.623C1.25531 20.9967 1.40966 13.892 5.85084 9.45081C10.292 5.00964 17.3967 4.85529 22.023 8.98775L22.0364 8.97436L24.0596 10.9976C24.0596 10.9976 25.1483 9.78969 25.4872 9.45081Z"
            fill={color}
        />
    </svg>
);
