/**
 * @file PhotoAlbumlBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M9 5C8.44772 5 8 5.44772 8 6V8C8 8.55228 8.44772 9 9 9H39C39.5523 9 40 8.55228 40 8V6C40 5.44772 39.5523 5 39 5H9ZM5 15C5 13.8954 5.89543 13 7 13H41C42.1046 13 43 13.8954 43 15V31.6998L37.1606 25.8923C35.9429 24.6812 33.9791 24.67 32.7476 25.8671L15.1231 43H7C5.89543 43 5 42.1046 5 41V15ZM34.9345 29.3197L43 37.3413V41C43 42.1046 42.1046 43 41 43H20.8617L34.9345 29.3197ZM19 24C19 25.6569 17.6569 27 16 27C14.3431 27 13 25.6569 13 24C13 22.3431 14.3431 21 16 21C17.6569 21 19 22.3431 19 24Z"
            fill={color}
        />
    </svg>
);
