/**
 * @file PkBaseOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M3 9C2.44772 9 2 9.44772 2 10V10.4615V23V27V38C2 38.5523 2.44772 39 3 39H5C5.55228 39 6 38.5523 6 38V27H12C16.9706 27 21 22.9706 21 18C21 13.0294 16.9706 9 12 9H6H3.46154H3ZM12 23H6V13H12C14.7614 13 17 15.2386 17 18C17 20.7614 14.7614 23 12 23ZM25 10C25 9.44772 25.4477 9 26 9H28C28.5523 9 29 9.44772 29 10V21.8333L39.4014 9.69842C39.7813 9.25513 40.336 9 40.9199 9H43.9188C44.345 9 44.5758 9.49908 44.2998 9.82382L32.0652 24.2174L44.2744 38.1708C44.5573 38.4941 44.3277 39 43.8981 39H40.9186C40.3355 39 39.7814 38.7455 39.4014 38.3032L29.6964 27.0043L29 27.8235V38C29 38.5523 28.5523 39 28 39H26C25.4477 39 25 38.5523 25 38V10Z"
            fill={color}
        />
    </svg>
);
