/**
 * @file SearchBaseOutline
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M34.6655 33.6657L35.6661 32.4298C37.7528 29.8523 39 26.5772 39 23C39 14.7157 32.2843 8 24 8C15.7157 8 9 14.7157 9 23C9 31.2843 15.7157 38 24 38C27.5771 38 30.8521 36.7529 33.4297 34.6662L34.6655 33.6657ZM38.775 34.9467L45.5478 41.7196C45.9383 42.1101 45.9383 42.7433 45.5478 43.1338L44.1336 44.548C43.7431 44.9385 43.1099 44.9385 42.7194 44.548M42.7165 44.5451L35.9465 37.7752C32.6828 40.4173 28.5262 42 24 42C13.5066 42 5 33.4934 5 23C5 12.5066 13.5066 4 24 4C34.4934 4 43 12.5066 43 23C43 27.5263 41.4172 31.683 38.775 34.9467"
            fill={color}
        />
    </svg>
);
