/**
 * @file SearchBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M33 21C33 27.6274 27.6274 33 21 33C14.3726 33 9 27.6274 9 21C9 14.3726 14.3726 9 21 9C27.6274 9 33 14.3726 33 21ZM35.6728 31.4288C37.7679 28.4865 39 24.8871 39 21C39 11.0589 30.9411 3 21 3C11.0589 3 3 11.0589 3 21C3 30.9411 11.0589 39 21 39C24.8879 39 28.4878 37.7674 31.4304 35.6717L39.8299 44.0711C40.2204 44.4616 40.8536 44.4616 41.2441 44.0711L44.0725 41.2427C44.463 40.8522 44.463 40.219 44.0725 39.8285L35.6728 31.4288Z"
            fill={color}
        />
    </svg>
);
