/**
 * @file ServiceBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M12 19.2275V25H16C16.5523 25 17 25.4477 17 26V37C17 37.5523 16.5523 38 16 38H13C9.68629 38 7 35.3137 7 32V25V19.2275C7 9.40563 14.6113 3 24.0003 3C33.3892 3 41.0005 9.40563 41.0005 19.2275V25H41V32C41 35.3137 38.3137 38 35 38H32C31.4477 38 31 37.5523 31 37V26C31 25.4477 31.4477 25 32 25H36.0005V19.2275C36.0005 12.5533 31.0305 8 24.0003 8C16.97 8 12 12.5533 12 19.2275ZM26.8292 41H35C35.5523 41 36 41.4477 36 42C36 42.5523 35.5523 43 35 43H26.8292C26.4173 44.1652 25.3061 45 23.9999 45C22.343 45 20.9999 43.6569 20.9999 42C20.9999 40.3431 22.343 39 23.9999 39C25.3061 39 26.4173 39.8348 26.8292 41Z"
            fill={color}
        />
    </svg>
);
