/**
 * @file ShoppingBagBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M6.90496 5.90013C6.95818 4.83571 7.83672 4 8.90247 4H39.0975C40.1632 4 41.0418 4.83571 41.095 5.90012L42.895 41.9001C42.9521 43.0425 42.0413 44 40.8975 44H7.10247C5.95867 44 5.04785 43.0425 5.10496 41.9001L6.90496 5.90013ZM19 13V18C19 20.7614 21.2385 23 24 23C26.7614 23 29 20.7614 29 18V13H33V18C33 22.9706 28.9705 27 24 27C19.0294 27 15 22.9706 15 18V13H19Z"
            fill={color}
        />
    </svg>
);
