/**
 * @file TextButtonBaseFilled
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M7 5C5.89543 5 5 5.89543 5 7V41C5 42.1046 5.89543 43 7 43H41C42.1046 43 43 42.1046 43 41V7C43 5.89543 42.1046 5 41 5H7ZM15 17C15 16.4477 15.4477 16 16 16H32C32.5523 16 33 16.4477 33 17V19C33 19.5523 32.5523 20 32 20H26V33C26 33.5523 25.5523 34 25 34H23C22.4477 34 22 33.5523 22 33V20H16C15.4477 20 15 19.5523 15 19V17Z"
            fill={color}
        />
    </svg>
);
