/**
 * @file ViewListBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import React from "react";
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <path d="M14 4.5H2V3.5H14V4.5Z" fill={color} />
        <path d="M14 8.5H2V7.5H14V8.5Z" fill={color} />
        <path d="M2 12.5H14V11.5H2V12.5Z" fill={color} />
    </svg>
);
