/**
 * @file ArticleBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-article-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M35 7C35 5.89543 34.1046 5 33 5H7C5.89543 5 5 5.89543 5 7V35C5 39.4183 8.58172 43 13 43H32H35H37C41.4183 43 45 39.4183 45 35V23C45 21.8954 44.1046 21 43 21H35V7ZM35 39H37C39.2091 39 41 37.2091 41 35V25H35V39ZM15.1016 16C14.5493 16 14.1016 16.4477 14.1016 17V19C14.1016 19.5523 14.5493 20 15.1016 20H25.1016C25.6538 20 26.1016 19.5523 26.1016 19V17C26.1016 16.4477 25.6538 16 25.1016 16H15.1016ZM15.1016 24C14.5493 24 14.1016 24.4477 14.1016 25V27C14.1016 27.5523 14.5493 28 15.1016 28H25.1016C25.6538 28 26.1016 27.5523 26.1016 27V25C26.1016 24.4477 25.6538 24 25.1016 24H15.1016Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
