/**
 * @file CalendarBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-calendar-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M6 3V2H5V3H2.66667C2.29848 3 2 3.29848 2 3.66667V13.3333C2 13.7015 2.29848 14 2.66667 14H13.3333C13.7015 14 14 13.7015 14 13.3333V3.66667C14 3.29848 13.7015 3 13.3333 3H11V2H10V3H6ZM10 4.99854V4H6V5.00049H5V4H3V6H13V4H11V4.99854H10ZM13 7H3V13H13V7Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
