/**
 * @file CatalogueBaseOutline
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-catalogue-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M11 10C11 11.6569 9.65685 13 8 13C6.34315 13 5 11.6569 5 10C5 8.34315 6.34315 7 8 7C9.65685 7 11 8.34315 11 10ZM11 24C11 25.6569 9.65685 27 8 27C6.34315 27 5 25.6569 5 24C5 22.3431 6.34315 21 8 21C9.65685 21 11 22.3431 11 24ZM8 41C9.65685 41 11 39.6569 11 38C11 36.3431 9.65685 35 8 35C6.34315 35 5 36.3431 5 38C5 39.6569 6.34315 41 8 41ZM16 8C15.4477 8 15 8.44772 15 9V11C15 11.5523 15.4477 12 16 12H42C42.5523 12 43 11.5523 43 11V9C43 8.44772 42.5523 8 42 8H16ZM15 23C15 22.4477 15.4477 22 16 22H42C42.5523 22 43 22.4477 43 23V25C43 25.5523 42.5523 26 42 26H16C15.4477 26 15 25.5523 15 25V23ZM16 36C15.4477 36 15 36.4477 15 37V39C15 39.5523 15.4477 40 16 40H42C42.5523 40 43 39.5523 43 39V37C43 36.4477 42.5523 36 42 36H16Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
