/**
 * @file CheckBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-check-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M6.43397 9.92188L12.6566 3.69922L13.5759 4.61846L6.43397 11.7604L1.97461 7.301L2.89385 6.38176L6.43397 9.92188Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
