/**
 * @file ClockBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-clock-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24 3C12.402 3 3 12.402 3 24C3 35.598 12.402 45 24 45C35.598 45 45 35.598 45 24C45 12.402 35.598 3 24 3ZM22 11C22 10.4477 22.4477 10 23 10H25C25.5523 10 26 10.4477 26 11V24.3431L32.6066 30.9497C32.9971 31.3403 32.9971 31.9734 32.6066 32.364L31.1924 33.7782C30.8019 34.1687 30.1687 34.1687 29.7782 33.7782L22.7071 26.7071C22.6033 26.6033 22.5271 26.4824 22.4785 26.3534C22.1915 26.1777 22 25.8612 22 25.5V11Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
