/**
 * @file CollectionBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-collection-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M26.4648 39.7008C25.3844 39.1913 24.1329 39.1913 23.0525 39.7008L13.5144 44.1988C12.0839 44.8734 10.4733 43.6991 10.6782 42.1308L12.0301 31.7802C12.1865 30.583 11.7937 29.3792 10.9614 28.5046L3.75062 20.9277C2.65645 19.7779 3.27321 17.8729 4.83361 17.5826L15.1818 15.6575C16.361 15.4381 17.3795 14.7012 17.9566 13.6498L23.0054 4.4529C23.7649 3.0695 25.7524 3.0695 26.5118 4.4529L31.5607 13.6498C32.1378 14.7012 33.1563 15.4381 34.3354 15.6575L44.6837 17.5826C46.2441 17.8729 46.8608 19.7779 45.7667 20.9277L38.5559 28.5046C37.7236 29.3792 37.3308 30.583 37.4872 31.7802L38.8391 42.1308C39.044 43.6991 37.4334 44.8734 36.0029 44.1988L26.4648 39.7008Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
