/**
 * @file CopperBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-copper-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M41 24C41 33.3888 33.3888 41 24 41C14.6112 41 7 33.3888 7 24C7 14.6112 14.6112 7 24 7C33.3888 7 41 14.6112 41 24ZM24 45C35.598 45 45 35.598 45 24C45 12.402 35.598 3 24 3C12.402 3 3 12.402 3 24C3 35.598 12.402 45 24 45ZM31.0711 22.5857L25.4142 16.9289C24.6332 16.1478 23.3668 16.1478 22.5858 16.9289L16.9289 22.5857C16.1479 23.3668 16.1479 24.6331 16.9289 25.4141L22.5858 31.071C23.3668 31.852 24.6332 31.852 25.4142 31.071L31.0711 25.4141C31.8521 24.6331 31.8521 23.3668 31.0711 22.5857Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
