/**
 * @file CopyBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-copy-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M39 8H15C15 5.79086 16.7909 4 19 4H42C43.1046 4 44 4.89451 44 5.99908V12V29C44 31.2091 42.2091 33 40 33V9C40 8.44772 39.5523 8 39 8ZM9 39V15H33V39H9ZM5 13C5 11.8954 5.89543 11 7 11H35C36.1046 11 37 11.8954 37 13V41C37 42.1046 36.1046 43 35 43H7C5.89543 43 5 42.1046 5 41V13Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
