/**
 * @file DownSmallBaseFilledPc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-down-small-base-filled-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M8.31235 10.6096C8.15222 10.8097 7.84778 10.8097 7.68765 10.6096L4.5199 6.64988C4.31038 6.38797 4.49685 6 4.83225 6L11.1678 6C11.5032 6 11.6896 6.38797 11.4801 6.64988L8.31235 10.6096Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
