/**
 * @file EditBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-edit-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M10.881 1.73738L14.1243 4.98076L14.8314 4.27365L11.5881 1.03027L10.881 1.73738Z"
                    fill={props.color}
                />
                <path
                    d="M2.35119 13.8637L5.96415 13.1411L13.2618 5.84347L10.0184 2.60009L2.72077 9.89769L1.99818 13.5107C1.9562 13.7206 2.14127 13.9056 2.35119 13.8637ZM10.0184 4.0143L11.8475 5.84347L5.47114 12.2199L3.18468 12.6772L3.64197 10.3907L10.0184 4.0143Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
