/**
 * @file ForkBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-fork-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <mask id="path-1-inside-1_2860_28230" fill={props.color}>
                    <rect x="6" y="2" width="4" height="4" rx="0.8" />
                </mask>
                <rect
                    x="6"
                    y="2"
                    width="4"
                    height="4"
                    rx="0.8"
                    stroke={props.color}
                    stroke-width="2"
                    mask="url(#path-1-inside-1_2860_28230)"
                />
                <mask id="path-2-inside-2_2860_28230" fill={props.color}>
                    <rect x="2" y="10" width="4" height="4" rx="0.8" />
                </mask>
                <rect
                    x="2"
                    y="10"
                    width="4"
                    height="4"
                    rx="0.8"
                    stroke={props.color}
                    stroke-width="2"
                    mask="url(#path-2-inside-2_2860_28230)"
                />
                <mask id="path-3-inside-3_2860_28230" fill={props.color}>
                    <rect x="10" y="10" width="4" height="4" rx="0.8" />
                </mask>
                <rect
                    x="10"
                    y="10"
                    width="4"
                    height="4"
                    rx="0.8"
                    stroke={props.color}
                    stroke-width="2"
                    mask="url(#path-3-inside-3_2860_28230)"
                />
                <path
                    d="M12 10V8.6C12 8.54477 11.9552 8.5 11.9 8.5H4.1C4.04477 8.5 4 8.54477 4 8.6V10"
                    stroke={props.color}
                />
                <rect x="7.5" y="6" width="1" height="3" fill={props.color} />
            </svg>
        );
    },
});
