/**
 * @file JumpPageBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-jump-page-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M41 8.61089C41 7.72122 40.2787 7 39.3891 7H11.0565C10.512 7 10.0676 7.43561 10.0567 7.97999L10.0203 9.79903C10.0091 10.3566 10.4562 10.8155 11.0138 10.819L34.1268 10.9631L6.64791 38.6189C6.25864 39.0107 6.25864 39.6459 6.64791 40.0377L8.17212 41.5717C8.56139 41.9635 9.19252 41.9635 9.58179 41.5717L37.0373 13.9395L37.1809 36.9861C37.1844 37.5438 37.6434 37.9909 38.2009 37.9797L40.02 37.9433C40.5644 37.9324 41 37.488 41 36.9435V8.61089Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
