/**
 * @file LocationBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-location-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M33.3935 31.4144C31.4168 33.9017 26.9787 38.01 24.0225 40.6536C21.1015 38.0054 16.6546 33.8619 14.5037 31.3195C11.4979 27.7667 10 23.48 10 19.7778C10 12.2152 16.221 6 24 6C31.779 6 38 12.2152 38 19.7778C38 23.3768 36.3405 27.7062 33.3935 31.4144ZM22.7066 44.8516C23.4486 45.5154 24.5564 45.5212 25.304 44.8637C27.9557 42.5315 33.9435 37.1514 36.525 33.9031C39.8915 29.6671 42 24.4862 42 19.7778C42 9.95939 33.9411 2 24 2C14.0589 2 6 9.95939 6 19.7778C6 24.49 7.87587 29.6785 11.4499 33.9031C14.1865 37.1378 20.0902 42.5111 22.7066 44.8516ZM30 20C30 23.3137 27.3137 26 24 26C20.6863 26 18 23.3137 18 20C18 16.6863 20.6863 14 24 14C27.3137 14 30 16.6863 30 20Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
