/**
 * @file MaleBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-male-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g clip-path="url(#clip0_22951:61607)">
                    <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M24.7188 1.5C12.2923 1.5 2.21875 11.5736 2.21875 24C2.21875 36.4264 12.2923 46.5 24.7188 46.5C37.1452 46.5 47.2188 36.4264 47.2188 24C47.2188 11.5736 37.1452 1.5 24.7188 1.5ZM26.3086 9.60553L26.3089 9.60585L32.6728 15.9697C32.9657 16.2626 32.9657 16.7375 32.6728 17.0304L31.6121 18.091C31.3192 18.3839 30.8443 18.3839 30.5514 18.091L26.2186 13.7582L26.2186 22.6244C30.4753 23.3385 33.7188 27.0405 33.7188 31.5C33.7188 36.4706 29.6893 40.5 24.7188 40.5C19.7482 40.5 15.7188 36.4706 15.7188 31.5C15.7188 27.0405 18.9621 23.3386 23.2186 22.6245L23.2186 13.7561L18.884 18.0908C18.5911 18.3837 18.1162 18.3837 17.8233 18.0908L16.7626 17.0301C16.4697 16.7373 16.4697 16.2624 16.7626 15.9695L24.1873 8.54487C24.4802 8.25197 24.955 8.25197 25.2479 8.54487L25.2481 8.54509L26.3086 9.60553ZM24.7188 37.5C28.0325 37.5 30.7188 34.8137 30.7188 31.5C30.7188 28.1863 28.0325 25.5 24.7188 25.5C21.405 25.5 18.7188 28.1863 18.7188 31.5C18.7188 34.8137 21.405 37.5 24.7188 37.5Z"
                        fill={props.color}
                    />
                </g>
                <defs>
                    <clipPath id="clip0_22951:61607">
                        <rect
                            width="48"
                            height="48"
                            fill={props.color}
                            transform="translate(0.71875)"
                        />
                    </clipPath>
                </defs>
            </svg>
        );
    },
});
