/**
 * @file NewsBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-news-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M14.8469 33H39V9H9V37.6775L14.8469 33ZM16.25 37H41C42.1046 37 43 36.1046 43 35V7C43 5.89543 42.1046 5 41 5H7C5.89543 5 5 5.89543 5 7V42C5 43.677 6.93986 44.4481 8.24939 43.4005L16.25 37Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M14.5 24C15.8807 24 17 22.8807 17 21.5C17 20.1193 15.8807 19 14.5 19C13.1193 19 12 20.1193 12 21.5C12 22.8807 13.1193 24 14.5 24ZM33.5 24C34.8807 24 36 22.8807 36 21.5C36 20.1193 34.8807 19 33.5 19C32.1193 19 31 20.1193 31 21.5C31 22.8807 32.1193 24 33.5 24ZM26.5 21.5C26.5 22.8807 25.3807 24 24 24C22.6193 24 21.5 22.8807 21.5 21.5C21.5 20.1193 22.6193 19 24 19C25.3807 19 26.5 20.1193 26.5 21.5Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
