/**
 * @file NewsBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-news-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M5 7C5 5.89543 5.89543 5 7 5H41C42.1046 5 43 5.89543 43 7V35C43 36.1046 42.1046 37 41 37H16.25L8.24939 43.4005C6.93986 44.4481 5 43.5158 5 41.8387V35V30V7ZM14 24C15.6569 24 17 22.6569 17 21C17 19.3431 15.6569 18 14 18C12.3431 18 11 19.3431 11 21C11 22.6569 12.3431 24 14 24ZM37 21C37 22.6569 35.6569 24 34 24C32.3431 24 31 22.6569 31 21C31 19.3431 32.3431 18 34 18C35.6569 18 37 19.3431 37 21ZM24 24C25.6569 24 27 22.6569 27 21C27 19.3431 25.6569 18 24 18C22.3431 18 21 19.3431 21 21C21 22.6569 22.3431 24 24 24Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
