/**
 * @file NoticeBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-notice-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M27 43.125V6.375L14.8303 15.6891C14.7038 15.6721 14.5746 15.6633 14.4434 15.6633H8.88C7.28942 15.6633 6 16.9528 6 18.5433V30.3731C6 31.9636 7.28942 33.2531 8.88 33.2531H14.1018L27 43.125Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M41.4 8.7C42.3941 10.0255 42.1255 11.9059 40.8 12.9L34.8 17.4C33.4745 18.3941 31.5941 18.1255 30.6 16.8C29.6059 15.4745 29.8745 13.5941 31.2 12.6L37.2 8.1C38.5255 7.10589 40.4059 7.37452 41.4 8.7Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M41.4 40.8C42.3941 39.4745 42.1255 37.5941 40.8 36.6L34.8 32.1C33.4745 31.1059 31.5941 31.3745 30.6 32.7C29.6059 34.0255 29.8745 35.9059 31.2 36.9L37.2 41.4C38.5255 42.3941 40.4059 42.1255 41.4 40.8Z"
                    fill={props.color}
                />
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M30 24.75C30 26.4069 31.3431 27.75 33 27.75H40C41.6569 27.75 43 26.4069 43 24.75C43 23.0931 41.6569 21.75 40 21.75H33C31.3431 21.75 30 23.0931 30 24.75Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
