/**
 * @file OthersBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-others-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M10 10V18H18V10H10ZM8 6C6.89543 6 6 6.89543 6 8V20C6 21.1046 6.89543 22 8 22H20C21.1046 22 22 21.1046 22 20V8C22 6.89543 21.1046 6 20 6H8ZM10 38V30H18V38H10ZM6 28C6 26.8954 6.89543 26 8 26H20C21.1046 26 22 26.8954 22 28V40C22 41.1046 21.1046 42 20 42H8C6.89543 42 6 41.1046 6 40V28ZM30 38V30H38V38H30ZM26 28C26 26.8954 26.8954 26 28 26H40C41.1046 26 42 26.8954 42 28V40C42 41.1046 41.1046 42 40 42H28C26.8954 42 26 41.1046 26 40V28ZM30 18V10H38V18H30ZM26 8C26 6.89543 26.8954 6 28 6H40C41.1046 6 42 6.89543 42 8V20C42 21.1046 41.1046 22 40 22H28C26.8954 22 26 21.1046 26 20V8Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
