/**
 * @file PauseBaseOutline
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-pause-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M14 5C13.4477 5 13 5.44772 13 6V42C13 42.5523 13.4477 43 14 43H16C16.5523 43 17 42.5523 17 42V6C17 5.44772 16.5523 5 16 5H14ZM32 5C31.4477 5 31 5.44772 31 6V42C31 42.5523 31.4477 43 32 43H34C34.5523 43 35 42.5523 35 42V6C35 5.44772 34.5523 5 34 5H32Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
