/**
 * @file PauseBaseFilled
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-pause-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M13 5C12.4477 5 12 5.44772 12 6V42C12 42.5523 12.4477 43 13 43H19C19.5523 43 20 42.5523 20 42V6C20 5.44772 19.5523 5 19 5H13ZM29 5C28.4477 5 28 5.44772 28 6V42C28 42.5523 28.4477 43 29 43H35C35.5523 43 36 42.5523 36 42V6C36 5.44772 35.5523 5 35 5H29Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
