/**
 * @file PlayBaseOutline
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-play-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M12 39.0339L36.5967 24.0001L12 8.96623L12 39.0339ZM38.6827 27.413C41.2347 25.8533 41.2347 22.1469 38.6827 20.5871L14.0861 5.55327C11.4206 3.92414 8 5.84238 8 8.96623V39.0339C8 42.1577 11.4206 44.076 14.086 42.4468L38.6827 27.413Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
