/**
 * @file QrCodeBaseOutline
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-qr-code-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M10 10V18H18V10H10ZM8 6C6.89543 6 6 6.89543 6 8V20C6 21.1046 6.89543 22 8 22H20C21.1046 22 22 21.1046 22 20V8C22 6.89543 21.1046 6 20 6H8ZM10 30V38H18V30H10ZM8 26C6.89543 26 6 26.8954 6 28V40C6 41.1046 6.89543 42 8 42H20C21.1046 42 22 41.1046 22 40V28C22 26.8954 21.1046 26 20 26H8ZM27 26C26.4477 26 26 26.4477 26 27V41C26 41.5523 26.4477 42 27 42H29C29.5523 42 30 41.5523 30 41V27C30 26.4477 29.5523 26 29 26H27ZM32 27C32 26.4477 32.4477 26 33 26H35C35.5523 26 36 26.4477 36 27V35C36 35.5523 35.5523 36 35 36H33C32.4477 36 32 35.5523 32 35V27ZM39 26C38.4477 26 38 26.4477 38 27V41C38 41.5523 38.4477 42 39 42H41C41.5523 42 42 41.5523 42 41V27C42 26.4477 41.5523 26 41 26H39ZM32 39C32 38.4477 32.4477 38 33 38H35C35.5523 38 36 38.4477 36 39V41C36 41.5523 35.5523 42 35 42H33C32.4477 42 32 41.5523 32 41V39ZM30 18V10H38V18H30ZM26 8C26 6.89543 26.8954 6 28 6H40C41.1046 6 42 6.89543 42 8V20C42 21.1046 41.1046 22 40 22H28C26.8954 22 26 21.1046 26 20V8Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
