/**
 * @file RecordingBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-recording-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M42.1061 18.2229V29.7772L37 25.5958V22.4043L42.1061 18.2229ZM5 12.0001H33V36.0001H5V12.0001ZM41.2054 13.7905L37 17.2342V10.0001C37 8.89555 36.1046 8.00012 35 8.00012H3C1.89543 8.00012 1 8.89555 1 10.0001V38.0001C1 39.1047 1.89543 40.0001 3 40.0001H35C36.1046 40.0001 37 39.1047 37 38.0001V30.7659L41.2054 34.2096C43.164 35.8135 46.1061 34.4201 46.1061 31.8886V16.1115C46.1061 13.58 43.164 12.1866 41.2054 13.7905ZM13 17.0001C13 18.657 11.6569 20.0001 10 20.0001C8.34315 20.0001 7 18.657 7 17.0001C7 15.3433 8.34315 14.0001 10 14.0001C11.6569 14.0001 13 15.3433 13 17.0001Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
