/**
 * @file RefreshBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-refresh-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#4A96FF",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g opacity="0.01">
                    <rect
                        x="0.375"
                        y="0.375"
                        width="47.25"
                        height="47.25"
                        rx="2.625"
                        fill={props.color}
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M24 13.125C30.0061 13.125 34.875 17.9939 34.875 24C34.875 30.0061 30.0061 34.875 24 34.875C17.9939 34.875 13.125 30.0061 13.125 24C13.125 17.9939 17.9939 13.125 24 13.125Z"
                        stroke={props.color}
                        stroke-width="0.75"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M24 16.125C28.3492 16.125 31.875 19.6508 31.875 24C31.875 28.3492 28.3492 31.875 24 31.875C19.6508 31.875 16.125 28.3492 16.125 24C16.125 19.6508 19.6508 16.125 24 16.125Z"
                        stroke={props.color}
                        stroke-width="0.75"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M0 12.9375H48"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M0 24H48"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M0 35.25H48"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M24 48L24 0"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M35.25 48V0"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M12.75 48L12.75 0"
                        stroke={props.color}
                        stroke-width="0.75"
                    />
                    <path
                        opacity="0.2"
                        d="M1.125 46.875L46.875 1.125"
                        stroke={props.color}
                        stroke-width="0.75"
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M46.875 46.875L1.125 1.125"
                        stroke={props.color}
                        stroke-width="0.75"
                        stroke-linecap="square"
                    />
                    <path
                        d="M10.5 4.5375H37.5C39.1361 4.5375 40.4625 5.86386 40.4625 7.5V40.5C40.4625 42.1361 39.1361 43.4625 37.5 43.4625H10.5C8.86386 43.4625 7.5375 42.1361 7.5375 40.5V7.5C7.5375 5.86386 8.86386 4.5375 10.5 4.5375Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.075"
                        stroke-linecap="square"
                    />
                    <path
                        d="M4.5375 37.5V10.5C4.5375 8.86386 5.86386 7.5375 7.5 7.5375H40.5C42.1361 7.5375 43.4625 8.86386 43.4625 10.5V37.5C43.4625 39.1361 42.1361 40.4625 40.5 40.4625H7.5C5.86386 40.4625 4.5375 39.1361 4.5375 37.5Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.075"
                        stroke-linecap="square"
                    />
                    <path
                        d="M6.0375 39V9C6.0375 7.36386 7.36386 6.0375 9 6.0375H39C40.6361 6.0375 41.9625 7.36386 41.9625 9V39C41.9625 40.6361 40.6361 41.9625 39 41.9625H9C7.36386 41.9625 6.0375 40.6361 6.0375 39Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.075"
                        stroke-linecap="square"
                    />
                    <path
                        d="M24 4.5375C34.7488 4.5375 43.4625 13.2512 43.4625 24C43.4625 34.7488 34.7488 43.4625 24 43.4625C13.2512 43.4625 4.5375 34.7488 4.5375 24C4.5375 13.2512 13.2512 4.5375 24 4.5375Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.075"
                        stroke-linecap="square"
                    />
                </g>
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M36.7036 31.5C34.1359 35.8398 29.4078 38.75 24 38.75C15.8538 38.75 9.25 32.1462 9.25 24C9.25 23.4936 9.27552 22.9932 9.32533 22.5H5.30913C5.26996 22.9948 5.25 23.4951 5.25 24C5.25 34.3553 13.6447 42.75 24 42.75C30.6034 42.75 36.4095 39.3364 39.75 34.1776V36.75C39.75 37.1642 40.0858 37.5 40.5 37.5H42C42.4142 37.5 42.75 37.1642 42.75 36.75V29.25C42.75 28.905 42.5171 28.6144 42.1999 28.5269C42.2021 28.518 42.2043 28.509 42.2065 28.5H42H38.051H34.5C34.0858 28.5 33.75 28.8358 33.75 29.25V30.75C33.75 31.1642 34.0858 31.5 34.5 31.5H36.7036ZM38.6747 25.5C38.7245 25.0068 38.75 24.5064 38.75 24C38.75 15.8538 32.1462 9.25 24 9.25C18.5922 9.25 13.8641 12.1602 11.2964 16.5H13.5C13.9142 16.5 14.25 16.8358 14.25 17.25V18.75C14.25 19.1642 13.9142 19.5 13.5 19.5H9.94904H6H5.79348L5.80014 19.4731C5.48295 19.3856 5.25 19.095 5.25 18.75V11.25C5.25 10.8358 5.58579 10.5 6 10.5H7.5C7.91421 10.5 8.25 10.8358 8.25 11.25V13.8224C11.5905 8.66358 17.3966 5.25 24 5.25C34.3553 5.25 42.75 13.6447 42.75 24C42.75 24.5049 42.73 25.0052 42.6909 25.5H38.6747Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
