/**
 * @file SettingsBaseOutline
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-settings-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M9 15.3062L24 6.62203L39 15.3062L39 32.6938L24 41.378L9 32.6938L9 15.3062ZM22.9979 2.58018C23.6178 2.22132 24.3822 2.22132 25.0021 2.58018L42.0021 12.4223C42.6197 12.7799 43 13.4395 43 14.1531L43 33.8469C43 34.5606 42.6197 35.2202 42.0021 35.5778L25.0021 45.4199C24.3822 45.7788 23.6178 45.7788 22.9979 45.4199L5.99792 35.5778C5.38029 35.2202 5 34.5606 5 33.8469L5 14.1531C5 13.4395 5.38029 12.7799 5.99792 12.4223L22.9979 2.58018ZM24 29C21.2386 29 19 26.7614 19 24C19 21.2386 21.2386 19 24 19C26.7614 19 29 21.2386 29 24C29 26.7614 26.7614 29 24 29ZM15 24C15 28.9706 19.0294 33 24 33C28.9706 33 33 28.9706 33 24C33 19.0294 28.9706 15 24 15C19.0294 15 15 19.0294 15 24Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
