/**
 * @file SettlementBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-settlement-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M41 24C41 33.3888 33.3888 41 24 41C14.6112 41 7 33.3888 7 24C7 14.6112 14.6112 7 24 7C33.3888 7 41 14.6112 41 24ZM45 24C45 35.598 35.598 45 24 45C12.402 45 3 35.598 3 24C3 12.402 12.402 3 24 3C35.598 3 45 12.402 45 24ZM20.4949 15.741C20.1862 15.2781 19.6667 15 19.1103 15C17.7811 15 16.9884 16.4813 17.7256 17.5872L20.0009 21H19.1C18.2163 21 17.5 21.7163 17.5 22.6C17.5 23.4837 18.2163 24.2 19.1 24.2H22.4V26.1992H19.1C18.2163 26.1992 17.5 26.9156 17.5 27.7992C17.5 28.6829 18.2163 29.3992 19.1 29.3992H22.4V32.4C22.4 33.2837 23.1163 34 24 34C24.8837 34 25.6 33.2837 25.6 32.4V29.3992H28.9C29.7837 29.3992 30.5 28.6829 30.5 27.7992C30.5 26.9156 29.7837 26.1992 28.9 26.1992H25.6V24.2H28.9C29.7837 24.2 30.5 23.4837 30.5 22.6C30.5 21.7163 29.7837 21 28.9 21H28.0009L30.2761 17.5872C31.0133 16.4813 30.2206 15 28.8915 15C28.3351 15 27.8155 15.2781 27.5068 15.741L24.0009 21L20.4949 15.741Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
