/**
 * @file SubmitBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-submit-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M40.3535 14.3535C40.7441 14.7441 40.7441 15.3772 40.3535 15.7678L20.7071 35.4142C20.3166 35.8047 19.6834 35.8047 19.2929 35.4142L9.64644 25.7678C9.25591 25.3772 9.25591 24.7441 9.64644 24.3535L10.7979 23.202C11.1865 22.8135 11.8157 22.8112 12.2071 23.197L20 30.8787L37.7929 13.2025C38.1838 12.8141 38.8152 12.8152 39.2048 13.2048L40.3535 14.3535Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
