/**
 * @file TemplateBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-template-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "black",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7.10156 5C5.99699 5 5.10156 5.89543 5.10156 7V20C5.10156 21.1046 5.99699 22 7.10156 22H20.1016C21.2061 22 22.1016 21.1046 22.1016 20V7C22.1016 5.89543 21.2061 5 20.1016 5H7.10156ZM7.10156 26C5.99699 26 5.10156 26.8954 5.10156 28V41C5.10156 42.1046 5.99699 43 7.10156 43H41.1016C42.2061 43 43.1016 42.1046 43.1016 41V28C43.1016 26.8954 42.2061 26 41.1016 26H7.10156ZM26.1016 17C26.1016 16.4477 26.5493 16 27.1016 16H41.1016C41.6538 16 42.1016 16.4477 42.1016 17V19C42.1016 19.5523 41.6538 20 41.1016 20H27.1016C26.5493 20 26.1016 19.5523 26.1016 19V17ZM27.1016 7C26.5493 7 26.1016 7.44772 26.1016 8V10C26.1016 10.5523 26.5493 11 27.1016 11H41.1016C41.6538 11 42.1016 10.5523 42.1016 10V8C42.1016 7.44772 41.6538 7 41.1016 7H27.1016Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
