/**
 * @file UndoBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-undo-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 49 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7.6005 14.8994C7.01472 15.4852 7.01472 16.435 7.6005 17.0208L16.7359 26.1562C17.148 26.5683 17.8237 26.5421 18.2027 26.0994L19.3915 24.7107C19.7339 24.3107 19.7075 23.7138 19.3312 23.3456L13.8674 17.9999H36.5C37.8807 17.9999 39 19.1192 39 20.4999V33.4999C39 34.8807 37.8807 35.9999 36.5 35.9999H8C7.44772 35.9999 7 36.4477 7 36.9999V38.9999C7 39.5522 7.44772 39.9999 8 39.9999H37.5C40.5376 39.9999 43 37.5375 43 34.4999V19.4999C43 16.4624 40.5376 13.9999 37.5 13.9999H13.8023L19.7023 8.27412C20.1285 7.86044 20.1023 7.16855 19.646 6.78828L18.2015 5.58457C17.8042 5.25346 17.22 5.27996 16.8543 5.64568L7.6005 14.8994Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
