/**
 * @file UploadBaseOutline
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../interface";

export default Vue.defineComponent({
    name: "icon-upload-base-outline",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M25.0607 6.0398C24.4749 5.45402 23.5251 5.45402 22.9393 6.0398L13.7329 15.2462C13.3479 15.6312 13.3417 16.2535 13.7189 16.6461L14.8025 17.7739C15.1869 18.1741 15.8237 18.1847 16.2213 17.7975L22 12.1696V31C22 31.5523 22.4477 32 23 32H25C25.5523 32 26 31.5523 26 31V12.1696L31.7787 17.7975C32.1763 18.1847 32.8131 18.1741 33.1975 17.7739L34.2811 16.6461C34.6583 16.2535 34.6521 15.6312 34.2671 15.2462L25.0607 6.0398ZM9 38.9933V25C9 24.4477 8.55228 24 8 24H6C5.44772 24 5 24.4477 5 25V40.9933C5 42.0979 5.89543 42.9933 7 42.9933L41 42.9933C42.1046 42.9933 43 42.0978 43 40.9933V24.9933C43 24.441 42.5523 23.9933 42 23.9933H40C39.4477 23.9933 39 24.441 39 24.9933V38.9933L9 38.9933Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
