/**
 * @file ViewListBaseOutlinePc
 * @author Auto Generated by IconGarden
 */

import Vue from "vue";
import { IIconProps } from "../type";

export default Vue.defineComponent({
    name: "icon-view-list-base-outline-pc",
    props: {
        size: {
            type: [Number, String],
            default: 16,
        },
        color: {
            type: String,
            default: "#131212",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path d="M14 4.5H2V3.5H14V4.5Z" fill={props.color} />
                <path d="M14 8.5H2V7.5H14V8.5Z" fill={props.color} />
                <path d="M2 12.5H14V11.5H2V12.5Z" fill={props.color} />
            </svg>
        );
    },
});
