/**
 * @file WarnBaseFilled
 * @author Auto Generated by IconGarden
 */

import { defineComponent } from "vue";
import { IIconProps } from "../interface";

export default defineComponent({
    name: "icon-warn-base-filled",
    props: {
        size: {
            type: [Number, String],
            default: 48,
        },
        color: {
            type: String,
            default: "#4A96FF",
        },
    },
    setup: (props: IIconProps) => {
        return () => (
            <svg
                width={props.size}
                height={props.size}
                viewBox="0 0 48 48"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <g opacity="0.01">
                    <rect
                        x="0.5"
                        y="0.5"
                        width="47"
                        height="47"
                        rx="3.5"
                        fill={props.color}
                        stroke={props.color}
                    />
                    <path
                        opacity="0.2"
                        d="M24 13.25C29.9371 13.25 34.75 18.0629 34.75 24C34.75 29.9371 29.9371 34.75 24 34.75C18.0629 34.75 13.25 29.9371 13.25 24C13.25 18.0629 18.0629 13.25 24 13.25Z"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M24 16.25C28.2802 16.25 31.75 19.7198 31.75 24C31.75 28.2802 28.2802 31.75 24 31.75C19.7198 31.75 16.25 28.2802 16.25 24C16.25 19.7198 19.7198 16.25 24 16.25Z"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M0 12.9375H48"
                        stroke={props.color}
                    />
                    <path opacity="0.2" d="M0 24H48" stroke={props.color} />
                    <path opacity="0.2" d="M0 35.25H48" stroke={props.color} />
                    <path opacity="0.2" d="M24 48L24 0" stroke={props.color} />
                    <path opacity="0.2" d="M35.25 48V0" stroke={props.color} />
                    <path
                        opacity="0.2"
                        d="M12.75 48L12.75 0"
                        stroke={props.color}
                    />
                    <path
                        opacity="0.2"
                        d="M1.125 46.875L46.875 1.125"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        opacity="0.2"
                        d="M46.875 46.875L1.125 1.125"
                        stroke={props.color}
                        stroke-linecap="square"
                    />
                    <path
                        d="M11.5 4.55H36.5C38.6815 4.55 40.45 6.31848 40.45 8.5V39.5C40.45 41.6815 38.6815 43.45 36.5 43.45H11.5C9.31848 43.45 7.55 41.6815 7.55 39.5V8.5C7.55 6.31848 9.31848 4.55 11.5 4.55Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M4.55 36.5V11.5C4.55 9.31848 6.31848 7.55 8.5 7.55H39.5C41.6815 7.55 43.45 9.31848 43.45 11.5V36.5C43.45 38.6815 41.6815 40.45 39.5 40.45H8.5C6.31848 40.45 4.55 38.6815 4.55 36.5Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M6.05 38V10C6.05 7.81848 7.81848 6.05 10 6.05H38C40.1815 6.05 41.95 7.81848 41.95 10V38C41.95 40.1815 40.1815 41.95 38 41.95H10C7.81848 41.95 6.05 40.1815 6.05 38Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                    <path
                        d="M24 4.55C34.7419 4.55 43.45 13.2581 43.45 24C43.45 34.7419 34.7419 43.45 24 43.45C13.2581 43.45 4.55 34.7419 4.55 24C4.55 13.2581 13.2581 4.55 24 4.55Z"
                        fill={props.color}
                        fill-opacity="0.04"
                        stroke={props.color}
                        stroke-width="0.1"
                        stroke-linecap="square"
                    />
                </g>
                <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44ZM26.25 26C26.25 26.5523 25.8023 27 25.25 27H22.75C22.1977 27 21.75 26.5523 21.75 26V14.5C21.75 13.9477 22.1977 13.5 22.75 13.5H25.25C25.8023 13.5 26.25 13.9477 26.25 14.5V26ZM25.25 34.5C25.8023 34.5 26.25 34.0523 26.25 33.5V31C26.25 30.4477 25.8023 30 25.25 30H22.75C22.1977 30 21.75 30.4477 21.75 31V33.5C21.75 34.0523 22.1977 34.5 22.75 34.5H25.25Z"
                    fill={props.color}
                />
            </svg>
        );
    },
});
