/**
 * @file CataloguelBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M11 11C11 12.6569 9.65685 14 8 14C6.34315 14 5 12.6569 5 11C5 9.34315 6.34315 8 8 8C9.65685 8 11 9.34315 11 11ZM11 25C11 26.6569 9.65685 28 8 28C6.34315 28 5 26.6569 5 25C5 23.3431 6.34315 22 8 22C9.65685 22 11 23.3431 11 25ZM8 42C9.65685 42 11 40.6569 11 39C11 37.3431 9.65685 36 8 36C6.34315 36 5 37.3431 5 39C5 40.6569 6.34315 42 8 42ZM16 8C15.4477 8 15 8.44772 15 9V13C15 13.5523 15.4477 14 16 14H42C42.5523 14 43 13.5523 43 13V9C43 8.44772 42.5523 8 42 8H16ZM15 23C15 22.4477 15.4477 22 16 22H42C42.5523 22 43 22.4477 43 23V27C43 27.5523 42.5523 28 42 28H16C15.4477 28 15 27.5523 15 27V23ZM16 36C15.4477 36 15 36.4477 15 37V41C15 41.5523 15.4477 42 16 42H42C42.5523 42 43 41.5523 43 41V37C43 36.4477 42.5523 36 42 36H16Z"
        fill="${color}"
    />
</svg>;
`;
