/**
 * @file CheckCircleBaseFilledPc
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        d="M7.80078 14.7998C11.6668 14.7998 14.8008 11.6658 14.8008 7.7998C14.8008 3.93381 11.6668 0.799805 7.80078 0.799805C3.93479 0.799805 0.800781 3.93381 0.800781 7.7998C0.800781 11.6658 3.93479 14.7998 7.80078 14.7998ZM4.30078 8.0063L5.00728 7.2998L6.80078 9.0928L10.5933 5.2998L11.3008 6.0073L6.80078 10.5068L4.30078 8.0063Z"
        fill="${color}"
    />
</svg>;
`;
