/**
 * @file CopyBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M39 8H15C15 5.79086 16.7909 4 19 4H42C43.1046 4 44 4.89451 44 5.99908V12V29C44 31.2091 42.2091 33 40 33V9C40 8.44772 39.5523 8 39 8ZM7 11C5.89543 11 5 11.8954 5 13V41C5 42.1046 5.89543 43 7 43H35C36.1046 43 37 42.1046 37 41V13C37 11.8954 36.1046 11 35 11H7Z"
        fill="${color}"
    />
</svg>;
`;
