/**
 * @file CreditCardBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M6 42C4.89543 42 4 41.1046 4 40V18H44V40C44 41.1046 43.1046 42 42 42H6ZM4 8V14H44V8C44 6.89543 43.1046 6 42 6H6C4.89543 6 4 6.89543 4 8ZM38 32H30V36H38V32Z"
        fill="${color}"
    />
</svg>;
`;
