/**
 * @file DirectoryBaseOutline
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M12 40V8H38V40H12ZM8 6C8 4.89543 8.89543 4 10 4H40C41.1046 4 42 4.89543 42 6V42C42 43.1046 41.1046 44 40 44H10C8.89543 44 8 43.1046 8 42V34H5C4.44772 34 4 33.5523 4 33V31C4 30.4477 4.44772 30 5 30H8V18H5C4.44772 18 4 17.5523 4 17V15C4 14.4477 4.44772 14 5 14H8V6ZM26 14C25.4477 14 25 14.4477 25 15V17C25 17.5523 25.4477 18 26 18H34C34.5523 18 35 17.5523 35 17V15C35 14.4477 34.5523 14 34 14H26Z"
        fill="${color}"
    />
</svg>;
`;
