/**
 * @file FlagBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        d="M5 6C5 4.89543 5.89543 4 7 4H39.8878C41.344 4 42.312 5.50637 41.707 6.8309L37.442 16.1691C37.201 16.6968 37.201 17.3032 37.442 17.8309L41.707 27.1691C42.312 28.4936 41.344 30 39.8878 30H7C5.89543 30 5 29.1046 5 28V6Z"
        fill="${color}"
    />
    <path
        d="M5 6C5 4.89543 5.89543 4 7 4H9C10.1046 4 11 4.89543 11 6V42C11 43.1046 10.1046 44 9 44H7C5.89543 44 5 43.1046 5 42V6Z"
        fill="${color}"
    />
</svg>;
`;
