/**
 * @file GiftBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M31.0129 3.573L35.2343 7.75758L31.9589 10.9999H41C42.1046 10.9999 43 11.8954 43 12.9999V18.9999H5V12.9999C5 11.8954 5.89543 10.9999 7 10.9999H16.0411L12.7657 7.7576L16.9871 3.57302L24 10.5151L31.0129 3.573ZM41 21.9998H7V40.9998C7 42.1043 7.89543 42.9998 9 42.9998H39C40.1046 42.9998 41 42.1043 41 40.9998V21.9998Z"
        fill="${color}"
    />
</svg>;
`;
