/**
 * @file MailBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M6 6C4.89543 6 4 6.89543 4 8V13.4697L23.9949 24.7031L44 13.3477V8C44 6.89543 43.1046 6 42 6H6ZM44 17.9472L24.0051 29.2969L4 18.0577V40C4 41.1046 4.89543 42 6 42H42C43.1046 42 44 41.1046 44 40V17.9472Z"
        fill="${color}"
    />
</svg>;
`;
