/**
 * @file MenuBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M5.99927 7C5.99927 6.44772 6.44698 6 6.99927 6H40.9993C41.5516 6 41.9993 6.44772 41.9993 7V11C41.9993 11.5523 41.5516 12 40.9993 12H6.99927C6.44698 12 5.99927 11.5523 5.99927 11V7ZM5.99927 22C5.99927 21.4477 6.44698 21 6.99927 21H40.9993C41.5516 21 41.9993 21.4477 41.9993 22V26C41.9993 26.5523 41.5516 27 40.9993 27H6.99927C6.44698 27 5.99927 26.5523 5.99927 26V22ZM6.99993 36C6.44765 36 5.99993 36.4477 5.99993 37V41C5.99993 41.5523 6.44765 42 6.99993 42H40.9999C41.5522 42 41.9999 41.5523 41.9999 41V37C41.9999 36.4477 41.5522 36 40.9999 36H6.99993Z"
        fill="${color}"
    />
</svg>;
`;
