/**
 * @file MicrophoneBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M15 12C15 7.02944 19.0294 3 24 3C28.9706 3 33 7.02944 33 12V23C33 27.9706 28.9706 32 24 32C19.0294 32 15 27.9706 15 23V12ZM10 23C10.5523 23 10.996 23.4493 11.0379 24C11.5485 30.7124 17.1568 36 24 36C30.8433 36 36.4515 30.7124 36.9621 24C37.004 23.4493 37.4477 23 38 23H40C40.5523 23 41.0031 23.4487 40.9711 24.0001C40.4921 32.2565 34.1209 38.9319 26 39.8836V44C26 44.5523 25.5523 45 25 45H23C22.4477 45 22 44.5523 22 44V39.8836C13.8791 38.9319 7.50792 32.2565 7.02895 24.0001C6.99696 23.4487 7.44773 23 8.00002 23H10Z"
        fill="${color}"
    />
</svg>;
`;
