/**
 * @file MoreBaseOutline
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M10 27C11.6569 27 13 25.6569 13 24C13 22.3431 11.6569 21 10 21C8.34315 21 7 22.3431 7 24C7 25.6569 8.34315 27 10 27ZM24 27C25.6569 27 27 25.6569 27 24C27 22.3431 25.6569 21 24 21C22.3431 21 21 22.3431 21 24C21 25.6569 22.3431 27 24 27ZM41 24C41 25.6569 39.6569 27 38 27C36.3431 27 35 25.6569 35 24C35 22.3431 36.3431 21 38 21C39.6569 21 41 22.3431 41 24Z"
        fill="${color}"
    />
</svg>;
`;
