/**
 * @file PieChartBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M44.906 22H26V3.09405C36.0016 4.03897 43.9611 11.9985 44.906 22ZM44.9766 25H23V3.02344C11.8664 3.54539 3 12.7373 3 24C3 35.598 12.402 45 24 45C35.2628 45 44.4547 36.1337 44.9766 25Z"
        fill="${color}"
    />
</svg>;
`;
