/**
 * @file RightBaseOutlinePc
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        d="M6.99479 4.00484L6.49964 3.51005L5.51005 4.50036L6.00521 4.99516L6.99479 4.00484ZM10 7.99742L10.4952 8.49221L10.9899 7.99706L10.4948 7.50226L10 7.99742ZM6.00484 11.0052L5.51005 11.5004L6.50037 12.49L6.99516 11.9948L6.00484 11.0052ZM6.00521 4.99516L9.5052 8.49258L10.4948 7.50226L6.99479 4.00484L6.00521 4.99516ZM9.50484 7.50263L6.00484 11.0052L6.99516 11.9948L10.4952 8.49221L9.50484 7.50263Z"
        fill="${color}"
    />
</svg>;
`;
