/**
 * @file ScanBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M36.8984 31.0007L39.8984 31.0003L42.8984 31V34V41.1538C42.8984 42.1734 42.003 43 40.8984 43H6.89844C5.79387 43 4.89844 42.1734 4.89844 41.1538V34.0044V31.0044H7.89844H10.8984V34V34.0044V37H13.8984H33.8984H36.8984V34V31.0007ZM11 11V14V17H8H5V14V6.84615C5 5.82655 5.89543 5 7 5H41C42.1046 5 43 5.82655 43 6.84615V14V17H40H37V14V11H34H14H11ZM6 21C5.44772 21 5 21.4477 5 22V26C5 26.5523 5.44772 27 6 27H42C42.5523 27 43 26.5523 43 26V22C43 21.4477 42.5523 21 42 21H6Z"
        fill="${color}"
    />
</svg>;
`;
