/**
 * @file ServiceBaseOutline
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M5 22V23V26V33C5 36.3137 7.68629 39 11 39H13C15.2091 39 17 37.2091 17 35V25C17 23.8954 16.1046 23 15 23H9V22C9 13.7157 15.7157 7 24 7C32.2843 7 39 13.7157 39 22V23H33C31.8954 23 31 23.8954 31 25V35C31 37.2091 32.7909 39 35 39H37C40.3137 39 43 36.3137 43 33V26V23V22C43 11.5066 34.4934 3 24 3C13.5066 3 5 11.5066 5 22ZM25 41C24.4477 41 24 41.4477 24 42V44C24 44.5523 24.4477 45 25 45H40C40.5523 45 41 44.5523 41 44V42C41 41.4477 40.5523 41 40 41H25ZM13 27H9V33C9 34.1046 9.89543 35 11 35H13V27ZM39 27H35V35H37C38.1046 35 39 34.1046 39 33V27Z"
        fill="${color}"
    />
</svg>;
`;
