/**
 * @file SortBaseOutlinePc
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        d="M11.6933 9.1582L8.00101 12.8505L4.30867 9.1582L3.60156 9.86531L7.57674 13.8405C7.81105 14.0748 8.19095 14.0748 8.42527 13.8405L12.4004 9.86531L11.6933 9.1582Z"
        fill="${color}"
    />
    <path
        d="M11.6445 6.83956L8.00009 3.15331L4.35566 6.83956L3.64453 6.1365L7.57341 2.16254C7.80827 1.92499 8.19191 1.92499 8.42676 2.16254L12.3557 6.1365L11.6445 6.83956Z"
        fill="${color}"
    />
</svg>;
`;
