/**
 * @file TextBaseOutline
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M40 12C40.5523 12 41 11.5523 41 11V9C41 8.44772 40.5523 8 40 8H25H23H8C7.44772 8 7 8.44772 7 9V11C7 11.5523 7.44772 12 8 12H22V41C22 41.5523 22.4477 42 23 42H25C25.5523 42 26 41.5523 26 41V12H40Z"
        fill="${color}"
    />
</svg>;
`;
