/**
 * @file UninterestedBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M32.2145 36.7C29.9919 38.1451 27.3914 39 24.6774 39C15.4609 39 9 32.035 9 24.6774C9 21.3991 9.89873 18.4212 11.4774 15.9628L32.2145 36.7ZM36.5057 32.5058L15.6701 11.6702C18.1833 9.97214 21.2678 9 24.6774 9C32.035 9 39 15.4609 39 24.6774C39 27.5109 38.0682 30.2207 36.5057 32.5058ZM24.6774 45C35.598 45 45 35.598 45 24.6774C45 12.402 35.598 3 24.6774 3C12.402 3 3 12.402 3 24.6774C3 35.598 12.402 45 24.6774 45Z"
        fill="${color}"
    />
</svg>;
`;
