/**
 * @file UpBaseOutlinePc
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 16, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        d="M12.4603 9.99868L11.541 10.9179L8.00064 7.37754L4.46025 10.9179L3.54102 9.99868L8.00064 5.53906L12.4603 9.99868Z"
        fill="${color}"
    />
    <path
        d="M4.0068 9.46224L3.512 9.9574L4.50232 10.947L4.99711 10.4518L4.0068 9.46224ZM7.99937 6.45704L8.49417 5.96188L7.99901 5.46709L7.50422 5.96224L7.99937 6.45704ZM11.0072 10.4522L11.5023 10.947L12.4919 9.95667L11.9967 9.46187L11.0072 10.4522ZM4.99711 10.4518L8.49453 6.95183L7.50422 5.96224L4.0068 9.46224L4.99711 10.4518ZM7.50458 6.95219L11.0072 10.4522L11.9967 9.46187L8.49417 5.96188L7.50458 6.95219Z"
        fill="${color}"
    />
</svg>;
`;
