/**
 * @file WalletBaseFilled
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../type";

export default ({ size = 48, color = "black" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M4 8C4 6.89543 4.89543 6 6 6H42C43.1046 6 44 6.89543 44 8V17H31C29.8954 17 29 17.8954 29 19V29C29 30.1046 29.8954 31 31 31H44V40C44 41.1046 43.1046 42 42 42H6C4.89543 42 4 41.1046 4 40V8ZM40 24C40 25.6569 38.6569 27 37 27C35.3431 27 34 25.6569 34 24C34 22.3431 35.3431 21 37 21C38.6569 21 40 22.3431 40 24Z"
        fill="${color}"
    />
</svg>;
`;
