/**
 * @file WalletBaseOutline
 * @author Auto Generated by IconGarden
 */
import { IIconProps } from "../interface";

export default ({ size = 48, color = "#131212" }: IIconProps) =>
    `<?xml version="1.0" encoding="UTF-8"?>
<svg
    width="${size}"
    height="${size}"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
>
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M7 38H41V10H7V38ZM3 40C3 41.1046 3.89543 42 5 42H43C44.1046 42 45 41.1046 45 40V8C45 6.89543 44.1046 6 43 6H5C3.89543 6 3 6.89543 3 8V40Z"
        fill="${color}"
    />
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M4 14H44V18H4V14Z"
        fill="${color}"
    />
    <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M30 32H38V36H30V32Z"
        fill="${color}"
    />
</svg>;
`;
